app_modules/customers/urls.py
from django.urls import path
from app_modules.customers import views

app_name = "customer"

urlpatterns = [
    # '''url for Customer model'''
    path("", views.CustomerListView.as_view(), name="customer_list"),
    path("create/", views.CustomerCreateView.as_view(), name="customer_create"),
    path('customer-list-ajax/', views.CustomerDataTablesAjaxPagination.as_view(), name='customer_list_ajax'),
    path("<int:pk>/update/", views.CustomerUpdateView.as_view(), name="customer_update"),
    path("delete/", views.CustomerDeleteAjaxView.as_view(), name="customer_delete"),
    path("create/load-sales-rep-ajax/", views.LoadSalesRep.as_view(), name="load_sales_rep"),

    path("get-discounts/", views.CustomerDiscountAjaxView.as_view(), name="get_customer_discount_table"),

    path("discounts/", views.DiscountListView.as_view(), name="discount_list"),
    path("discount-list-ajax/", views.DiscountListAjaxView.as_view(), name="discount_list_ajax"),
    path("discount/create/", views.DiscountCreateView.as_view(), name="discount_create"),
    path("discount/<int:pk>/update/", views.DiscountUpdateView.as_view(), name="discount_update"),
    path("discount/delete/", views.DiscountDeleteView.as_view(), name="discount_delete"),

    path("discount/search/", views.DiscountSearchAjaxView.as_view(), name="discount_search"),
    path("customer/search/", views.CustomerSearchAjaxView.as_view(), name="customer_search"),

    path("replacements/", views.ReplacementListView.as_view(), name="replacement_list"),
    path("replacement-list-ajax/", views.ReplacementListAjaxView.as_view(), name="replacement_list_ajax"),
    path("replacements/create/", views.ReplacementCreateView.as_view(), name="replacement_create"),
    path("replacements/<int:pk>/update/", views.ReplacementUpdateView.as_view(), name="replacement_update"),
    path("replacements/delete/", views.ReplacementDeleteView.as_view(), name="replacement_delete"),

    #'''url for customer details'''
    path("<int:pk>/details/", views.CustomerDetailsView.as_view(), name="customer_details"),
    path("customer-lock/", views.CustomerBillingLockAjaxView.as_view(), name="customer_billing_lock"),

    path("<int:pk>/customer-address-info/", views.CustomerAddressListView.as_view(), name="customer_addressinfo"),
    
    path("customer-addressinfo-billing-list-ajax/", views.CustomerBillingAddressDataTablesAjaxPagination.as_view(), name="customer_addressinfo_billing_list_ajax"),
    path("<int:pk>/customer-billing-addressinfo/create/", views.CustomerBillingAddressInfoCreateView.as_view(), name="customer_billing_addressinfo_create"),
    path("<int:customer_id>/customer-billing-addressinfo/<int:pk>/update/", views.CustomerBillingAddressInfoUpdateView.as_view(), name="customer_billing_addressinfo_update"),
    path("customer-billing-addressinfo/delete/", views.CustomerBillingAddressInfoDeleteAjaxView.as_view(), name="customer_billing_addressinfo_delete"),

    path("customer-addressinfo-shipping-list-ajax/", views.CustomerShippingAddressDataTablesAjaxPagination.as_view(), name="customer_addressinfo_shipping_list_ajax"),
    path("<int:pk>/customer-shipping-addressinfo/create/", views.CustomerShippingAddressInfoCreateView.as_view(), name="customer_shipping_addressinfo_create"),
    path("<int:customer_id>/customer-shipping-addressinfo/<int:pk>/update/", views.CustomerShippingAddressInfoUpdateView.as_view(), name="customer_shipping_addressinfo_update"),
    path("customer-shipping-addressinfo/delete/", views.CustomerShippingAddressInfoDeleteAjaxView.as_view(), name="customer_shipping_addressinfo_delete"),

    path("<int:pk>/customer-document-info/create/", views.UploadDocumentsCreateView.as_view(), name="upload_document"),
    path("<int:customer_pk>/customer-document-info/<int:pk>/update/", views.UploadDocumentsUpdateView.as_view(), name="customer_document_update"),
    path("<int:pk>/customer-documents-info/", views.CustomerDocumentsListView.as_view(), name="customer_documents"),
    path("customer-document-list-ajax/", views.CustomerDocumentsDataTablesAjaxPagination.as_view(), name="customer_documents_list_ajax"),
    path("customer-document/delete/", views.CustomerDocumentDeleteAjaxView.as_view(), name="customer_document_delete"),

    path("<int:pk>/contact-add/create/", views.CustomerContactCreateView.as_view(), name="contact_add"),
    path("<int:pk>/customer-contact-ajax/", views.CustomerContactListView.as_view(), name="customer_contact_ajax"),
    path("customer-contact-list-ajax/", views.CustomerContactDataTableAjaxPagination.as_view(), name="customer_contact_list_ajax"),
    path("<int:customer_pk>/customer-contact-info/<int:pk>/update/", views.CustomerContactUpdateView.as_view(), name="customer_contact_update"),
    path("customer-contact/delete/", views.CustomerContactDeleteAjaxView.as_view(), name="customer_contact_delete"),

    path("<int:pk>/customer-creditmemo-ajax/", views.CustomerCreditMemoListView.as_view(), name="customer_creditmemo"),
    path("customer-credit-memo-list-ajax/", views.CustomerCreditMemoDataTableAjaxPagination.as_view(), name="customer_creditmemo_list_ajax"),

    path("<int:pk>/customer-order-ajax", views.CustomerOrderListView.as_view() , name="customer_order"),
    path("customer-order-list-ajax", views.CustomerOrderDataTableAjaxPagination.as_view() , name="customer_order_list_ajax"),

    path("<int:pk>/customer-replacement-ajax", views.CustomerReplacementListView.as_view() , name="customer_replacement"),
    path("customer-replacement-list-ajax", views.CustomerReplacementDataTableAjaxPagination.as_view() , name="customer_replacement_list_ajax"),
    path("customer-ledger-list-ajax", views.LedgerDataTableAjaxPagination.as_view() , name="customer_ledger_list_ajax"),

    path("<int:pk>/customer-ledger-ajax", views.CustomerLedgerListView.as_view() , name="customer_ledger_list"),
    path("<int:pk>/customer-payment-history-ajax", views.CustomerPaymentHistoryListView.as_view() , name="customer_payment_history"),
    path("customer-payment-history-list-ajax", views.CustomerPaymentHistoryDataTableAjaxPagination.as_view() , name="customer_payment_history_list_ajax"),
    path("<int:pk>/payment-details/", views.PaymentHistoryDetailsView.as_view(), name="payment_history_detail"),
    

    # '''url for Payment model'''
    path("payment/", views.PaymentListView.as_view(), name="payment_list"),
    path("payment/create/", views.PaymentCreateView.as_view(), name="payment_create"),
    path('payment-list-ajax/', views.PaymentDataTablesAjaxPagination.as_view(), name='payment_list_ajax'),
    path("payment/<int:pk>/update/", views.PaymentUpdateView.as_view(), name="payment_update"),
    path("payment/delete/", views.PaymentDeleteAjaxView.as_view(), name="payment_delete"),
    path("load-customer-for-payment-ajax", views.LoadCustomerForPaymentAjax.as_view(), name="load_customer_for_payment_ajax"),
    path("customer-bill-list-ajax", views.CustomerBillListView.as_view(), name="customer_bill_list_ajax"),
    path('<int:pk>/payment-list-ajax/', views.PaymentAjaxView.as_view(), name='payment_model_ajax'),

    # '''url for Sales Route model'''
    path("sales-route/", views.SalesRouteListView.as_view(), name="sales_route_list"),
    path("sales-route/create/", views.SalesRouteCreateView.as_view(), name="sales_route_create"),
    path('sales-route-list-ajax/', views.SalesRouteDataTablesAjaxPagination.as_view(), name='sales_route_list_ajax'),
    path("sales-route/<int:pk>/update/", views.SalesRouteUpdateView.as_view(), name="sales_route_update"),
    path("sales-route/delete/", views.SalesRouteDeleteAjaxView.as_view(), name="sales_route_delete"),
    path("load-customer-salesrep-ajax", views.LoadCustomerSalesrepAjax.as_view(), name="load_customer_sales_rep"),

    # '''url for Price Level model'''
    # path("price-level/", views.PricelevelListView.as_view(), name="price_level_list"),
    # path("price-level/create/", views.PricelevelCreateView.as_view(), name="price_level_create"),
    # path('price-level-list-ajax/', views.PricelevelDataTablesAjaxPagination.as_view(), name='price_level_list_ajax'),
    # path("price-level/<int:pk>/update/", views.PricelevelUpdateView.as_view(), name="price_level_update"),
    # path("price-level/delete/", views.PricelevelDeleteAjaxView.as_view(), name="price_level_delete"),

    #'''url for Product Price level'''
    path('price-level-product-ajax/', views.PricelevelProductDataTablesAjaxPagination.as_view(), name='price_level_product_list'),
    path('price-level-product-update-ajax/', views.PricelevelProductUpdateDataTablesAjaxPagination.as_view(), name='price_level_product_update'),
    path('<int:pk>/customer-log-list-ajax/', views.CustomerLogAjaxView.as_view(), name='customer_log_ajax'),
    path('customer-log-list-ajax-datatable/', views.CustomerLogDatatableAjaxView.as_view(), name='customer_log_ajax_datatable'),


    # """" url for import csv

    path("customer-create-from-csv/", views.CustomerCreateFromCSVFormView.as_view(), name="customer_create_from_csv"),
    path("zone-create-from-csv/", views.ZoneCreateFromCSVFormView.as_view(), name="zone_create_from_csv"),
    #''' url for Zone '''
    path('zone-list/', views.ZoneListView.as_view(), name="zone_list"),
    path('zone-list-ajax/', views.ZoneDataTablesAjaxPagination.as_view(), name='zone_list_ajax'),
    path('zone-create/', views.ZoneCreateView.as_view(), name="zone_create"),
    path('zone-update/<int:pk>/', views.ZoneUpdateView.as_view(), name="zone_update"),
    path('zone-delete/', views.ZoneDeleteAjaxView.as_view(), name="zone_delete"),

    # For delete all Customer And Zone:
    path('customer-delete-all/', views.AllCustomerDeleteView.as_view(), name="customer_delete_all"),
    path('zone-delete-all/', views.AllZoneDeleteView.as_view(), name="zone_delete_all"),

    
]

unity_wholesale/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from app_modules.users.views import HomeView, DasboardTemplateView , CustomPasswordChangeView

from allauth.account import views as allauth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("dashboard/",DasboardTemplateView.as_view(), name="dashboard"),
    path("company/", include('app_modules.company.urls'), name="company"),
    path("product/",include("app_modules.product.urls")),
    path("users/", include('app_modules.users.urls')),
    path("vendors/", include('app_modules.vendors.urls')),
    path("order/", include('app_modules.order.urls')),
    path('accounts/password/change/',CustomPasswordChangeView.as_view(),name='account_change_password'),
    # path("accounts/password/set/", allauth_views.password_set, name="account_set_password"),
    # path("accounts/logout/", allauth_views.logout, name="account_logout"),
    # path("accounts/signup/", allauth_views.signup, name="account_signup"),
    # path("accounts/password/reset/", allauth_views.password_reset, name="account_reset_password"),
    path("accounts/", include("allauth.urls")),
    path("", HomeView.as_view(), name="home_view"),
    path("customers/", include('app_modules.customers.urls'), name="customers"),
    path("purchase-order/",include('app_modules.purchase_order.urls')),
    path("credit-memo/",include('app_modules.credit_memo.urls')),
    path("reports/",include('app_modules.reports.urls')),
    path("expanse-management/",include('app_modules.expanse_management.urls')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/customer/custom_input.html
<input type="number" value="{{price_level_product.custom_price}}" name="custom_price" id="custom_price-{{price_level_product.id}}" class="form-control" placeholder="Custom Price" >

templates/customer/customer_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
List Customer
{% endblock title %}

{% comment %} {% block style %}
<style>
    .table-responsive {
        display: inline-table;
        width: 100%;
    }
</style>
{% endblock style %} {% endcomment %}

{% block bodycontent %}
<link rel="stylesheet" href="{% static 'css/switch.css' %}">

<div class="users-list-filter px-2">
  <div class="row border rounded py-2 mb-2 mx-n2">
    
    <div class="col-12 col-sm-6 col-lg-3">
        <label for="status-list-customer">Status</label>
        <fieldset class="form-group">
          <select id="status-list-customer" class="form-control">
            <option value="">All</option>
            {% for data in status_choices %}
            <option value="{{data.0}}">{{data.1}}</option>
            {% endfor %}
          </select>
        </fieldset>
    </div>
    <div class="col-12 col-sm-6 col-lg-3">
      <label for="status-list-zone">Customer Zone</label>
      <fieldset class="form-group">
        <select id="status-list-zone" class="form-control">
          <option value="">All</option>
          {% for zone in customer_zones %}
          <option value="{{zone.id}}">{{zone.zone_code}}</option>
          {% endfor %}
        </select>
      </fieldset>
    </div>
    <div class="col-12 col-sm-6 col-lg-3">
      {% if request.user.role == "super admin" %}
      <label for="customers-list-company">Company</label>
      <fieldset class="form-group">
        <select id="customers-list-company" class="form-control">
          <option value="">All</option>
            {% for company in companies %}
            <option value="{{company.company_name}}">{{company.company_name|title}}</option>
            {% endfor %}
          </select>
        </fieldset>
        {% endif %}
      </div>
    <div class="col-12 col-sm-6 col-lg-2">
    </div>
    
    <div class="col-12 col-sm-6 col-lg-1 d-flex align-items-center">
        <button type="reset" class="btn btn-primary btn-block customers-list-clear glow mb-0">Clear</button>
    </div>
</div>
</div>




<section id="file-export">
  <div class="row">
      <div class="col-12">
          <div class="card">
            <div class="card-header">
              <div class="d-flex flex-sm-row flex-column justify-content-between">
                <h4 class="card-title align-self-center">Customer List</h4>
                 <div>
                  {% if request.user.role in "company admin, super admin" %}
                  <a data-url="{% url 'customer:customer_delete_all' %}" id="customer_delete_all" class="btn btn-danger ml-sm-1">Delete All</a>
                  <a href="{% url 'customer:customer_create_from_csv' %}" class="btn btn-primary ml-sm-1">Import CSV</a>
                  {% endif %}
                  <a href="{% url 'customer:customer_create' %}" class="btn btn-primary ml-sm-1">Add</a>
                </div>
              </div>
            </div>
              <div class="card-content ">
                  <div class="card-body">
                      <div class="table-responsive ">
                          <table class="table table-striped table-bordered file-export" id="table">
                              <thead>
                                  <tr>
                                    <th>Sr. no</th>
                                    <th>Shop Name</th>
                                    <th>Type</th>
                                    <th>Area</th>
                                    <th>Zone</th>
                                    <th>Due Amount</th>
                                    {% comment %} {% if user.role == 'super admin' %}
                                    <th>Company Name</th>
                                    {% endif %} {% endcomment %}
                                    <th class="text-center">Lock Status</th>
                                    <th class="text-center">Status</th>
                                    {% comment %} <th>Tax Id</th>
                                    <th>Terms</th>
                                    <th>Store Open Time</th>
                                    <th>Store Close Time</th> {% endcomment %}
                                    <th class="text-center" style="width: 13%;">Actions</th>
                                  </tr>
                              </thead>
                              <tbody>
                              </tbody>
                          </table>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>

  <div class="modal fade text-left" id="default" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-dialog" role="document" style="max-width: 1200px;">
      <div class="modal-content" id="customer_log_modal">
      </div>
    </div>
  </div>
</section>


{% endblock %}

{% block script %}
    
<script>
    $('#customers-list-company, #status-list-customer, #status-list-zone').select2({
        width: "100%",
    });
      
    function set_filters(){
      var data = {}
      data["company"] = $("#customers-list-company").val()
      data["status"] = $("#status-list-customer").val()
      data["zone"] = $("#status-list-zone").val()
      return data
    }

    var role = false;

    if("{{request.user.role}}" == "company admin" || "{{request.user.role}}" == "super admin"){
      role = true;
    }
    

    function initialize_datatable(){
      $('#table').DataTable({

        columnDefs: [{
            orderable: false,
            targets: [-1, -4],
          },
          {
            targets: [-4],
            visible: role // new variable true or false based on user role.
          }
        ],
        order: [[0, 'desc']],

        // Ajax for pagination
        processing: true,
        language: {
            processing: '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading...</span>'
        },
        serverSide: true,
        ajax: {
            url: '{% url "customer:customer_list_ajax" %}',
            type: 'get',
            data: set_filters(), // this line also in dropdown filter
        },
        columns: [
            // data: json key from prepare_results, name: model field name
            { data: 'id', name: 'id' },
            { data: 'customer_name', name: 'customer_name' },
            { data: 'customer_type', name: 'customer_type' },
            { data: 'area', name: 'area' },
            { data: 'zone', name: 'zone' },
            { data: 'due_amount', render: function ( number ) {return number.toLocaleString('en-IN', {maximumFractionDigits: 2, style: 'currency', currency: 'INR'})},name: 'due_amount' },
            { data: 'is_locked', name: 'is_locked' },
            {% comment %} {% if user.role == 'super admin' %}
            { data: 'company', name: 'company' },
            {% endif %} {% endcomment %}
            { data: 'status', name: 'status' },
            {% comment %} { data: 'tax_id', name: 'tax_id' },
            { data: 'terms', name: 'terms' },
            { data: 'store_open_time', name: 'store_open_time' },
            { data: 'store_close_time', name: 'store_close_time' }, {% endcomment %}
            { data: 'actions', name: 'actions' }
        ],
        rowCallback: function (nRow, aData, iDisplayIndex) {
            var oSettings = this.fnSettings();
            $("td:first", nRow).html(oSettings._iDisplayStart + iDisplayIndex + 1);
            return nRow;
        },

    });
}

//this for above dropdown filteration
    initialize_datatable();

        $("#customers-list-company, #status-list-customer, #status-list-zone").on("change", function () {
          // t.search($(this).val()).draw();
          $("#table").DataTable().destroy();
          initialize_datatable()
        });

        //$(".customers-list-clear").on("click",function(){
        $(document).on('click', '.customers-list-clear' , function (){
          $("#customers-list-company").val(null).trigger('change');
          $("#status-list-customer").val(null).trigger('change');
          $("#status-list-zone").val(null).trigger('change');
          $("#table").DataTable().destroy();
          //$("#users-list-role option[value='']").attr("selected", "selected")
          initialize_datatable()
        })
    //end

</script>
<script>
    $(document).on('click', '.ajax-delete-btn' , function (e){
    var id = $(this).data("id")
    var name = $(this).data("title")
    if(name == "None"){
        name = ""
    }
    var url = $(this).data("url")
    var delete_ele = $(this)


    Swal.fire({
        html: `Are you sure you want to delete <b>${name}</b> ?`,
        icon: 'question',
        showCloseButton: true,
        showCancelButton: true,
        confirmButtonColor: "#7442DB",
    }).then((result) => {
        
        /* Read more about isConfirmed, isDenied below */
        if (result.isConfirmed) {
            $.ajax({
                type: "POST",
                url: url,
                data: {
                    "id": id,
                    "csrfmiddlewaretoken": '{{ csrf_token }}'
                },
                success: function (data) {
                $('#table').DataTable().ajax.reload(null, false);
                if (data["message"]){
                    $.toast({
                        text: data.message,
                        position: 'bottom-right',
                        stack: false,
                        icon: 'success',                    
                    })
                }
            }    
            });
        }
    })
    })
</script>

<script>
  $(document).on('click', '.customer-log-history-btn' , function (e) {
    url = $(this).data("url")
    htmx.ajax('GET', 
        url, 
        {target:'#customer_log_modal', 
        swap:'innerHTML', 
    }).then(() => {
        $("#default").show()
    });
  })

  $(document).on("click", "#customer_delete_all", function(){
    var url = $(this).data("url")

    Swal.fire({
        html: `Are you sure you want to delete all customers ?`,
        icon: 'question',
        showCloseButton: true,
        showCancelButton: true,
        confirmButtonColor: "#7442DB",
    }).then((result) => {
        
        /* Read more about isConfirmed, isDenied below */
        if (result.isConfirmed) {
            $.ajax({
                type: "POST",
                url: url,
                data: {
                    "csrfmiddlewaretoken": '{{ csrf_token }}'
                },
                success: function (data) {
                $('#table').DataTable().ajax.reload(null, false);
                if (data["message"]){
                    $.toast({
                        text: data.message,
                        position: 'bottom-right',
                        stack: false,
                        icon: 'success',                    
                    })
                }
            }    
            });
        }
    })
  })
</script>

<script>
  $(document).on('click', '.customer-detail-btn', function(e){
    localStorage.setItem("data" , "customerLog");
  })

  $(document).on('change', '.lock-switch', function(e){
    const val = String($(this).prop('checked')).replaceAll(' ','');
    const customer_id = $(this).data("id");

    $.ajax({
      url: "{% url 'customer:customer_billing_lock' %}",
      type: "POST",
      data: {
        'csrfmiddlewaretoken': "{{ csrf_token }}",
        'value': val,
        'customer_id': customer_id,
      },
      success: function(data) {
        $.toast({
          text: data.message,
          position: "bottom-right",
          stack: false,
          icon: data.level,
        });
      },
      error: function(xhr, ajaxOptions, thrownError) {
          //console.log(thrownError);
      }
    });
  })

</script>

{% endblock script %}

templates/customer/zone_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
List Zone
{% endblock title %}

{% comment %} {% block style %}
<style>
    .table-responsive {
        display: inline-table;
        width: 100%;
    }
</style>
{% endblock style %} {% endcomment %}

{% block bodycontent %}

{% comment %} <div class="users-list-filter px-2">
  <div class="row border rounded py-2 mb-2 mx-n2">
    
    <div class="col-12 col-sm-6 col-lg-3">
    </div>
    <div class="col-12 col-sm-6 col-lg-3">
      </div>
    <div class="col-12 col-sm-6 col-lg-5">
    </div>
    
    <div class="col-12 col-sm-6 col-lg-1 d-flex align-items-center">
        <button type="reset" class="btn btn-primary btn-block customers-list-clear glow mb-0">Clear</button>
    </div>
</div>
</div> {% endcomment %}




<section id="file-export">
  <div class="row">
      <div class="col-12">
          <div class="card">
            <div class="card-header">
              <div class="d-flex flex-sm-row flex-column justify-content-between">
                <h4 class="card-title align-self-center">Zone List</h4>
                <div>
                  {% if request.user.role in "company admin,super admin" %}
                  <a data-url="{% url 'customer:zone_delete_all' %}" class="btn btn-danger ml-sm-1" id="all_zone_delete">Delete All</a>
                  <a href="{% url 'customer:zone_create_from_csv' %}" class="btn btn-primary ml-sm-1">Import CSV</a>
                  {% endif %}
                  <a href="{% url 'customer:zone_create' %}" class="btn btn-primary ml-sm-1">Add</a>
                </div>
              </div>
            </div>
              <div class="card-content ">
                  <div class="card-body">
                      <div class="table-responsive ">
                          <table class="table table-striped table-bordered file-export" id="table">
                              <thead>
                                  <tr>
                                    <th>Sr. no</th>
                                    <th>Zone Code</th>
                                    <th>Zone Description</th>
                                    <th>Actions</th>
                                  </tr>
                              </thead>
                              <tbody>
                              </tbody>
                          </table>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>

  <div class="modal fade text-left" id="default" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-dialog" role="document" style="max-width: 1200px;">
      <div class="modal-content" id="customer_log_modal">
      </div>
    </div>
  </div>
</section>


{% endblock %}

{% block script %}
    
<script>
    $('#customers-list-company').select2({
        width: "100%",
      });
    $('#status-list-customer').select2({
        width: "100%",
      });
      
//this for above dropdown filteration
      /*function set_filters(){
        var data = {}
        data["company"] = $("#customers-list-company").val()
        data["status"] = $("#status-list-customer").val()
        return data
      }*/
    //end
      

    function initialize_datatable(){
    $('#table').DataTable({

        columnDefs: [{
            orderable: false,
            targets: -1,
        },],
        order: [[0, 'desc']],

        // Ajax for pagination
        processing: true,
        language: {
          processing: '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading...</span>'
        },
        serverSide: true,
        ajax: {
            url: '{% url "customer:zone_list_ajax" %}',
            type: 'get',
            //data: set_filters(), // this line also in dropdown filter
        },
        columns: [
            // data: json key from prepare_results, name: model field name
            { data: 'id', name: 'id' },
            { data: 'zone_code', name: 'zone_code' },
            { data: 'zone_description', name: 'zone_description' },
            { data: 'actions', name: 'actions' }
        ],
        rowCallback: function (nRow, aData, iDisplayIndex) {
            var oSettings = this.fnSettings();
            $("td:first", nRow).html(oSettings._iDisplayStart + iDisplayIndex + 1);
            return nRow;
        },

    });
}

//this for above dropdown filteration
    initialize_datatable();

        /*$("#customers-list-company").on("change", function () {
          // t.search($(this).val()).draw();
          $("#table").DataTable().destroy();
          initialize_datatable()
        });

        $("#status-list-customer").on("change", function () {
            // t.search($(this).val()).draw();
            $("#table").DataTable().destroy();
            initialize_datatable()
          });

        //$(".customers-list-clear").on("click",function(){
        $(document).on('click', '.customers-list-clear' , function (){
          $("#customers-list-company").val(null).trigger('change');
          $("#status-list-customer").val(null).trigger('change');
          $("#table").DataTable().destroy();
          //$("#users-list-role option[value='']").attr("selected", "selected")
          initialize_datatable()
        })*/
    //end

</script>
<script>
    $(document).on('click', '.ajax-delete-btn, #all_zone_delete' , function (e){
    var id = $(this).data("id")
    var name = $(this).data("title")
    var url = $(this).data("url")
    
    if(name == "None"){
        name = ""
    }

    var html = "";
    if(name){
      html = `Are you sure you want to delete <b>${name}</b> ?`;
    }
    else{
      html = `Are you sure you want to delete all zones ?`;
    }

    var data = {"csrfmiddlewaretoken": '{{ csrf_token }}'};
    if(id){
      data["id"] = id;
    }

    Swal.fire({
        html: html,
        icon: 'question',
        showCloseButton: true,
        showCancelButton: true,
        confirmButtonColor: "#7442DB",
    }).then((result) => {
        
        /* Read more about isConfirmed, isDenied below */
        if (result.isConfirmed) {
            $.ajax({
                type: "POST",
                url: url,
                data: data,
                success: function (data) {
                $('#table').DataTable().ajax.reload(null, false);
                if (data["message"]){
                    $.toast({
                        text: data.message,
                        position: 'bottom-right',
                        stack: false,
                        icon: 'success',                    
                    })
                }
            }    
            });
        }
    })
    })
</script>

<script>
  $(document).on('click', '.customer-log-history-btn' , function (e) {
    url = $(this).data("url")
    htmx.ajax('GET', 
        url, 
        {target:'#customer_log_modal', 
        swap:'innerHTML', 
    }).then(() => {
        $("#default").show()
    });
})
</script>

<script>
  $(document).on('click', '.customer-detail-btn', function(e){
    localStorage.setItem("data" , "orderList");
  })
</script>

{% endblock script %}