app_modules/purchase_order/urls.py
from django.urls import path
from app_modules.purchase_order.views import PurchaseOrderCreateView,GetVendorsAndProductsByCompanyAjax,AjaxGetProductDetails,AddProductInPurchaseList, PurchaseOrderListView,PurchaseOrderListAjax, PurchaseOrderUpdateView, AjaxGetUpdateProductDetails,GetProductFromBarcodeAjax

app_name = "purchase_order"

urlpatterns = [
    path("create/",PurchaseOrderCreateView.as_view(),name="purchase_order_create"),
    path("ajax-get-vendors-by-company/",GetVendorsAndProductsByCompanyAjax.as_view(),name="ajax_get_vendors_by_company"),
    path("ajax-get-product-details/",AjaxGetProductDetails.as_view(),name="ajax_get_product_details"),
    path("ajax-add-product-in-purchase-list/",AddProductInPurchaseList.as_view(),name="add_product_in_purchase_list"),
    path("",PurchaseOrderListView.as_view(), name="purchase_order_list"),
    path("purchase_order/data-table-ajax",PurchaseOrderListAjax.as_view(), name="purchase_order_list_ajax"),
    path("<int:pk>/update",PurchaseOrderUpdateView.as_view(),name="purchase_order_update"),
    path("ajax-get-update-product-details/",AjaxGetUpdateProductDetails.as_view(),name="ajax_get_update_product_details"),
    path("ajax-get-product-by-barcode/",GetProductFromBarcodeAjax.as_view(),name="ajax_get_product_by_barcode"),

    
]

app_modules/vendors/urls.py
from django.urls import path
from app_modules.vendors.views import VendorCreateView, VendorDataTablesAjaxPagination, VendorDeleteAjaxView, VendorListView, VendorUpdateView,VendorDetailsView,VendorReceviedListView,VendorReceivedBillDataTablesAjaxPagination,VendorDocumentsListView,VendorDocumentDataTablesAjaxPagination,VendorDocumentCreateView,VendorDocumentUpdateView,VendorDocumentDeleteAjaxView,VendorPaymentCreateView,LoadVendorAjax,VendorBillListView,VendorPaymentListView,VendorPaymentDataTablesAjaxPagination,VendorDetailsPaymentListView,VendorDetailsPaymentDataTablesAjaxPagination, VendorPaymentHistoryDetailsView, VendorPaymentAjaxView
app_name = "vendors"

urlpatterns = [
    # url for user
    path("", VendorListView.as_view(), name="vendor_list"),
    path("create/", VendorCreateView.as_view(), name="vendor_create"),
    path("<int:pk>/update/", VendorUpdateView.as_view(), name="vendor_update"),
    path("vendor-delete-ajax/", VendorDeleteAjaxView.as_view(), name="vendor_delete"),
    path("vendor-list-ajax/", VendorDataTablesAjaxPagination.as_view(), name="vendor_list_ajax"),
    path("<int:pk>/details/", VendorDetailsView.as_view(), name="vendor_details"),

    path("<int:pk>/vendor-received-bills/", VendorReceviedListView.as_view(), name="received_bills"),
    path("<int:pk>/vendor-upload-documents/", VendorDocumentsListView.as_view(), name="upload_documents"),

    path("<int:pk>/vendor-payment-history/", VendorDetailsPaymentListView.as_view(), name="payment_history"),
    path("vendor-payment-history-list-ajax/", VendorDetailsPaymentDataTablesAjaxPagination.as_view(), name="vendor_payment_history_list_ajax"),


    path("vendors-payment-history/", VendorPaymentListView.as_view(), name="payment_history_vendors"),
    path("vendors-payment-history-list-ajax/", VendorPaymentDataTablesAjaxPagination.as_view(), name="vendors_payment_history_list_ajax"),
    path("<int:pk>/payment-details/", VendorPaymentHistoryDetailsView.as_view(), name="payment_history_detail"),
    path('<int:pk>/vendor-payment-list-ajax/', VendorPaymentAjaxView.as_view(), name='payment_model_ajax'),
    
    
    path("vendor-recevied-bill-list-ajax/", VendorReceivedBillDataTablesAjaxPagination.as_view(), name="vendor_recevied_bill_list_ajax"),

    

    
    path("vendor-document-list-ajax/", VendorDocumentDataTablesAjaxPagination.as_view(), name="vendor_document_list_ajax"),
    path("<int:vendor_pk>/vendor-document-create/", VendorDocumentCreateView.as_view(), name="vendor_document_create"),
    path("<int:vendor_pk>/<int:pk>/vendor-document-update/", VendorDocumentUpdateView.as_view(), name="vendor_document_update"),
    path("vendor-document-delete-ajax/", VendorDocumentDeleteAjaxView.as_view(), name="vendor_document_delete"),

    path("vendor-payment-create/", VendorPaymentCreateView.as_view(), name="vendor_payment_create"),
    path("vendor-payment-create/load-vendor-ajax", LoadVendorAjax.as_view(), name="load_vendor_ajax"),
    path("vendor-payment-create/load-vendor-table-list-ajax", VendorBillListView.as_view(), name="load_vendor_table_list_ajax"),
    path("vendor-payment-create/load-vendor-table-list-ajax", VendorBillListView.as_view(), name="vendor_po_detailview"),
    

    

    

    
    
    
]
    

unity_wholesale/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from app_modules.users.views import HomeView, DasboardTemplateView , CustomPasswordChangeView

from allauth.account import views as allauth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("dashboard/",DasboardTemplateView.as_view(), name="dashboard"),
    path("company/", include('app_modules.company.urls'), name="company"),
    path("product/",include("app_modules.product.urls")),
    path("users/", include('app_modules.users.urls')),
    path("vendors/", include('app_modules.vendors.urls')),
    path("order/", include('app_modules.order.urls')),
    path('accounts/password/change/',CustomPasswordChangeView.as_view(),name='account_change_password'),
    # path("accounts/password/set/", allauth_views.password_set, name="account_set_password"),
    # path("accounts/logout/", allauth_views.logout, name="account_logout"),
    # path("accounts/signup/", allauth_views.signup, name="account_signup"),
    # path("accounts/password/reset/", allauth_views.password_reset, name="account_reset_password"),
    path("accounts/", include("allauth.urls")),
    path("", HomeView.as_view(), name="home_view"),
    path("customers/", include('app_modules.customers.urls'), name="customers"),
    path("purchase-order/",include('app_modules.purchase_order.urls')),
    path("credit-memo/",include('app_modules.credit_memo.urls')),
    path("reports/",include('app_modules.reports.urls')),
    path("expanse-management/",include('app_modules.expanse_management.urls')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_modules/purchase_order/views.py
from django.template.loader import render_to_string
from app_modules.purchase_order.models import PurchaseOrder,PurchaseOrderProducts
from app_modules.product.models import Barcode, Product, WarehouseProductStock, WarehouseProductStockHistory,Brand 
from app_modules.vendors.models import Vendor 
from app_modules.company.models import Company, Warehouse 
from app_modules.users.models import User 
from app_modules.purchase_order.forms import PurchaseOrderFrom,PurchaseOrderProductsForm
from django.views.generic import CreateView, View, ListView, UpdateView
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.urls import reverse, reverse_lazy
from django.template.loader import get_template
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import HttpResponseRedirect
from django.db.models import Q
from django_datatables_too.mixins import DataTableMixin
from django.contrib import messages
from app_modules.vendors.models import VendorBill
from app_modules.base.mixins import CompanyAdminLoginRequiredMixin

# Create your views here.

class PurchaseOrderCreateView(CompanyAdminLoginRequiredMixin,CreateView):
    model = PurchaseOrder
    form_class = PurchaseOrderFrom
    template_name = "purchase_order/purchase_order_form.html"
    success_url = reverse_lazy("purchase_order:purchase_order_list")
    
    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        form_kwargs["user"] = self.request.user
        return form_kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form2"] =  PurchaseOrderProductsForm
        return context
    

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.save()
        if self.request.user.role in[User.COMPANY_ADMIN,User.SALES_REPRESENTATIVE]:
            instance.company = self.request.user.company_users.first().company
            instance.save()
            
        product_ids=self.request.POST.get('product_id_list').split(',')
        
        for product_id in product_ids:
            self.add_product_list_in_purchase_order(instance,product_id)
        new_vendor_bill = VendorBill(purchase_order=instance, vendor = instance.vendor , bill_amount = instance.total_price , due_amount = instance.total_price)
        new_vendor_bill.save()
        messages.add_message(self.request, messages.SUCCESS, "Purchase Order Created ")
        return HttpResponseRedirect(reverse("purchase_order:purchase_order_list"))

    def add_product_list_in_purchase_order(self,purchase_order,product_id):
        purchase_order = purchase_order
        product_id = product_id
        product=Product.objects.get(id=product_id)
        unit_type = self.request.POST.get(f"product_{product_id}__unit_type")
        quantity = self.request.POST.get(f"product_{product_id}__quantity")
        total_pieces = self.request.POST.get(f"product_{product_id}__totalpieces")
        cost_price = self.request.POST.get(f"product_{product_id}__costprice")
        new_purchase_order=PurchaseOrderProducts(purchase_order=purchase_order,product=product,unit_type=unit_type,quantity=quantity,total_pieces=total_pieces,cost_price=cost_price)
        
        new_purchase_order.save()
    

class GetProductFromBarcodeAjax(View):
    def post(self, request):
        barcode_number = request.POST.get('barcode_number')
        product_id = None
        barcode_product_unit_type = None
        piece = 1
       
        product = list(Barcode.objects.filter(barcode_number=barcode_number).values('product','product_type'))
        for id in product:
            barcode_product_unit_type = id['product_type']
            product_id = id['product']
        product_list = Product.objects.filter(id = int(product_id)).all()

        for product_data in product_list:
            if product_data.box and barcode_product_unit_type == 'box' :
                piece = product_data.box_piece
            if product_data.case and barcode_product_unit_type == 'case':
                piece = product_data.case_piece

        data = {
            "product_id":product_id,
            "barcode_product_unit_type":barcode_product_unit_type.capitalize(),
            "piece":piece,
            }
        return JsonResponse(data, safe=False)



class GetVendorsAndProductsByCompanyAjax(View):

    template_name = "purchase_order/get_vendors_and_products_by_company.html"

    def post(self, request, *args, **kwargs):
        context={}
        data={}
        company_id = request.POST['company_id']
        
        company_vendors = Vendor.objects.filter(company = company_id,status=Vendor.ACTIVE)
        company_products = Product.objects.filter(company = company_id,status=Product.ACTIVE,brand__status = Brand.ACTIVE)

        context['company_vendors'] = company_vendors
        data['company_vendors']=render_to_string(self.template_name,context,request=request)
        context['company_vendors'] = None

        context['company_products'] = company_products
        data['company_products']=render_to_string(self.template_name,context,request=request)
        return JsonResponse(data)

class AjaxGetProductDetails(View):
    template_name = "purchase_order/get_product_details.html"
    
    def post(self, request, *args, **kwargs):
        context={}
        data={}
        product_id = request.POST['product_id']
        product = get_object_or_404(Product,id=product_id)

        context['product'] = product
        data['product_unit_type']=render_to_string(self.template_name,context,request=request)
        data['product_cost_price'] = product.cost_price
        return JsonResponse(data)



class AddProductInPurchaseList(View):
    #use this on company select
    template_name = "purchase_order/add_product_in_purchase_list.html"

    def post(self,request,*args, **kwargs):
        context={}
        data={}
        product_id = request.POST['product_id']
        unit_type = request.POST['unit_type']
        unit_type_text = request.POST['unit_type_text']
        unit_type_pieces = int(request.POST['unit_type_pieces'])
        quantity = int(request.POST['quantity'])
        cost_price = float(request.POST['cost_price'])

        product = get_object_or_404(Product, id = product_id)
        
        
        
        context['product'] = product
        context['unit_type'] = unit_type 
        context['unit_type_text'] = unit_type_text
        context['unit_type_pieces'] = unit_type_pieces
        context['quantity'] = quantity
        total_pieces = quantity * unit_type_pieces

        context['total_pieces'] = total_pieces
        context['cost_price'] = cost_price
        total_price = cost_price * total_pieces
        context['total_price'] = f'{"%.2f" % round(total_price, 2)}' 
        data['product_row']=render_to_string(self.template_name,context,request=request)
        return JsonResponse(data)
    


class PurchaseOrderListView(CompanyAdminLoginRequiredMixin,ListView):
    template_name = "purchase_order/purchase_order_list.html"
    model = PurchaseOrder

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["purhase_order_statuses"] = PurchaseOrder.STATUS_CHOICES
        context["companies"] = Company.objects.filter(status=Company.IS_ACTIVE)
        context["vendors"] = Vendor.objects.filter(status=Vendor.ACTIVE)
        if self.request.user.role in[User.COMPANY_ADMIN,User.SALES_REPRESENTATIVE]:
            company_admin_company = self.request.user.company_users.first().company
            context["vendors"] = Vendor.objects.filter(status=Vendor.ACTIVE, company = company_admin_company)

        return context

class PurchaseOrderListAjax(DataTableMixin,View):
    model = PurchaseOrder
    
    def get_queryset(self):
        qs = PurchaseOrder.objects.all().order_by("-id")

        if self.request.user.role == User.COMPANY_ADMIN or self.request.user.role == User.SALES_REPRESENTATIVE:
            company_id = list(self.request.user.company_users.all().values_list("company_id", flat=True))
            company_list = list(Company.objects.filter(id__in=company_id).values_list("id",flat=True))
            qs = qs.filter(company__in=company_list)


        purchase_order_list_company=self.request.GET.get("purchase_order_list_company")
        if purchase_order_list_company:
            companies=list(PurchaseOrder.objects.filter(company__in = purchase_order_list_company).values_list("id",flat=True))
            qs = qs.filter(id__in = companies)
        order_statuse = self.request.GET.get("purchase_order_status")
        if order_statuse:
            order_list = list(PurchaseOrder.objects.filter(status = order_statuse).values_list("id",flat=True))
            qs = qs.filter(id__in = order_list)
        purchase_order_vendor = self.request.GET.get("purchase_order_vendor")
        if purchase_order_vendor:
            qs = qs.filter(vendor__id=purchase_order_vendor)
        purchase_order_bill_number=self.request.GET.get("purchase_order_bill_number")
        if purchase_order_bill_number:
            qs = qs.filter(bill_number=purchase_order_bill_number)
        start_date = self.request.GET.get("from_date")
        end_date = self.request.GET.get("to_date")
        if end_date:
            result_payment = PurchaseOrder.objects.filter(bill_date__range = [start_date, end_date])
            qs = qs.filter(id__in=result_payment)
            return qs.order_by("-id")

        
        
        return qs.order_by("-id")
        

    def filter_queryset(self, qs):
        if self.search:
            return qs.filter(
                Q(bill_number__icontains=self.search) |
                Q(bill_date__icontains=self.search) | 
                Q(status__icontains=self.search)
            )
        return qs
    
    def _get_actions_buttons(self,obj):

templates/purchase_order/add_product_in_purchase_list.html
{% if purchase_order_products %}

{% for purchase_order_product in purchase_order_products %}
<tr data-id="product_{{purchase_order_product.product.id}}" product-id={{purchase_order_product.product.id}} purchase-order-product={{purchase_order_product.id}} class="product-row">
    <td data-title="product-id">{{forloop.counter}}</td>
    <td data-title="product-name">{{purchase_order_product.product.name}}<input type="hidden" name="product_{{purchase_order_product.product.id}}__id" value="{{purchase_order_product.product.id}}" /></td>
    <td data-title="unit-type-text">{{purchase_order_product.unit_type}} ({{purchase_order_product.get_unit_type_pieces}} pcs)<input type="hidden" name="product_{{purchase_order_product.product.id}}__unit_type" value="{{purchase_order_product.unit_type}}" /></td>
    <td data-title="quantity"><input type="number"  min="1"  name="product_{{purchase_order_product.product.id}}__quantity" class="form-control text-center" value="{{purchase_order_product.quantity}}" /><input type="hidden" name="product_{{purchase_order_product.product.id}}__quantity" value="{{purchase_order_product.quantity}}" /></td>
    <td data-title="total-pieces"><input type="number"  min="0.00" data-default-value="{{purchase_order_product.get_unit_type_pieces}}" name="product_{{purchase_order_product.product.id}}__totalpieces" class="form-control text-center" value="{{purchase_order_product.total_pieces}}" readonly /></td>
    <td data-title="cost-price"><input type="number"  min="0.00" step="0.01" name="product_{{purchase_order_product.product.id}}__costprice" class="form-control text-center" value="{{purchase_order_product.cost_price}}" /></td>
    <td data-title="total-price"><input type="number"  min="0.00" step="0.01" name="product_{{purchase_order_product.product.id}}__totalprice" class="form-control text-center product-total-price" value="{{purchase_order_product.get_total_price}}" readonly /></td>
    <td data-title="remove-product"><span class="btn-procuct-remove hover-pointer"><i class="ft-trash font-medium-3 danger btn-procuct-remove"></i></span></td>
</tr>
{% endfor %}
{% else %}
<tr data-id="product_{{product.id}}" product-id={{product.id}} purchase-order-product="new" class="product-row">
    <td data-title="product-id"></td>
    <td data-title="product-name">{{product.name}}<input type="hidden" name="product_{{product.id}}__id" value="{{product.id}}" /></td>
    <td data-title="unit-type-text">{{unit_type_text}}<input type="hidden" name="product_{{product.id}}__unit_type" value="{{unit_type}}" /></td>
    <td data-title="quantity"><input type="number"  min="1"  name="product_{{product.id}}__quantity" class="form-control text-center" value="{{quantity}}" /></td>
    <td data-title="total-pieces"><input type="number"  min="0.00" step="0.01" data-default-value="{{unit_type_pieces}}" name="product_{{product.id}}__totalpieces" class="form-control text-center" value="{{total_pieces}}" readonly /></td>
    <td data-title="cost-price"><input type="number"  min="0.00" step="0.01" name="product_{{product.id}}__costprice" class="form-control text-center" value="{{cost_price}}" /></td>
    <td data-title="total-price"><input type="number"  min="0.00" step="0.01" name="product_{{product.id}}__totalprice" class="form-control text-center product-total-price" value="{{total_price}}" readonly /></td>
    <td data-title="remove-product"><span class="btn-procuct-remove hover-pointer"><i class="ft-trash font-medium-3 danger btn-procuct-remove"></i></span></td>
</tr>
{% endif %}

templates/purchase_order/get_product_details.html
<option value="1" data-product-type="Piece">Piece</option>
{% if product.box %}
<option value="{{product.box_piece}}" data-product-type="Box" >Box ({{product.box_piece}} pcs)</option>
{% endif %}
{% if product.case %}
<option value="{{product.case_piece}}" data-product-type="Case" >Case ({{product.case_piece}} pcs)</option>
{% endif %}

templates/purchase_order/get_purchase_order_status.html
{% if purchase_order.status == 'completed' %}
<center><span class="badge bg-light-success">{{purchase_order.status.title}}</span></center>
{% elif purchase_order.status == 'reverted' %}
<center><span class="badge bg-light-danger">{{purchase_order.status.title}}</span></center>
{% elif purchase_order.status == 'pending' %}
<center><span class="badge bg-light-warning">{{purchase_order.status.title}}</span></center>
{% endif %}

templates/purchase_order/get_vendors_and_products_by_company.html
{% if company_vendors %}
    {% for company_vendor in company_vendors %}
        <option value="{{company_vendor.id}}">{{company_vendor.first_name}} {{company_vendor.last_name}}</option>
    {% endfor %}
{% endif %}

{% if company_products %}
    {% for company_product in company_products %}
        <option value="{{company_product.id}}">{{company_product.name}}</option>
    {% endfor %}
{% endif %}

templates/purchase_order/po_vendor_details.html
<a href="{% url 'vendors:vendor_details' vendor_id.id %}">{{vendor_id}}</a>

templates/purchase_order/purchase_order_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Purchase Order List{% endblock title %}
{% block bodycontent %}
<div class="company-list-filter px-2">
  <div class="row border rounded py-2 mb-2 mx-n2">
    <div class="col-12 col-sm-6 col-lg-2">
      <label for="users-list-company">Purchase Order Status</label>
      <fieldset class="form-group">
        <select id="purchase_order_status" class="form-control">
          <option value="">All</option>
          {% for purhase_order_status in purhase_order_statuses %}
          <option value="{{purhase_order_status.0}}">{{purhase_order_status.1}}</option>
          {% endfor %}
        </select>
      </fieldset>
    </div>

    <div class="col-12 col-sm-6 col-lg-2">
      <label for="purchase_order_vendor">Vendor</label>
      <fieldset class="form-group">
        <select id="purchase_order_vendor" class="form-control">
          <option value="">All</option>
          {% for obj in vendors %}
          <option value="{{obj.id}}">{{obj.first_name}}</option>
          {% endfor %}
        </select>
      </fieldset>
    </div>
    <div class="col-12 col-sm-6 col-lg-2">
      {% if request.user.role == "super admin" %}
      <label for="purchase_order_list_company">Company</label>
      <fieldset class="form-group">
        <select id="purchase_order_list_company" class="form-control">
          <option value="">All</option>
          {% for company in companies %}
          <option value="{{company.id}}">{{company.company_name|title}}</option>
          {% endfor %}
        </select>
      </fieldset>
      {% endif %}
      
    </div>

    <div class="col-12 col-sm-6 col-lg-2">
      {% comment %} <label for="purchase_order_bill_number">Bill Number</label>
      <fieldset class="form-group">
        <select id="purchase_order_bill_number" class="form-control">
          <option value="">All</option>
          {% for obj in object_list %}
          <option value="{{obj.bill_number}}">{{obj.bill_number}}</option>
          {% endfor %}
        </select>
      </fieldset> {% endcomment %}
    </div>

     <div class="col-12 col-sm-6 col-lg-3">
    </div>
    <div class="col-12 col-sm-6 col-lg-1 d-flex align-items-center">
      <button type="reset" class="btn btn-primary btn-block company-list-clear glow mb-0">Clear</button>
    </div>
  </div>

  {% comment %}<div class="row border rounded py-2 mb-2 mx-n2">
    <div class="col-12 col-sm-6 col-lg-3">
      <label for="id_receive_from_date">Receive From Date</label>
      <div class="" id="payment-receive-from-date">
          <input type="date" name="receive_from_date" class="form-control" placeholder="Receive From Date" id="id_receive_from_date">
      </div>
  </div>
  <div class="col-12 col-sm-6 col-lg-3">
      <label for="id_receive_to_date">Receive To Date</label>
      <div class="" id="payment-receive-to-date">
          <input type="date" name="receive_to_date" class="form-control" placeholder="Receive To Date" id="id_receive_to_date">
      </div>
  </div>
  <div class="col-12 col-sm-6 col-lg-2">
      <button type="submit" id="payments-list-date" class="btn btn-outline-primary glow mt-3">Search</button>
  </div>
  </div> {% endcomment %}

</div>


<section id="file-export">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <div class="d-flex flex-sm-row flex-column justify-content-between">
            <h4 class="card-title align-self-center">Purchase Order List</h4>
            <a href="{% url 'purchase_order:purchase_order_create' %}" class="btn btn-primary ml-sm-1">New Purchase Order</a>
          </div>
        </div>
        <div class="card-content ">
          <div class="card-body">
            <div class="">
              <table class="table table-striped table-bordered file-export dataTable" id="table">
                <thead>
                  <th>Sr No.</th>
                  <th>Company</th>
                  <th>Vendor</th>
                  <th>Bill Number</th>
                  <th>Bill Date</th>
                  <th>Total Price</th>
                  <th class="text-center">Status</th>
                  <th class="text-center">Actions</th>
                </thead>
                <tbody>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock bodycontent %}

{% block script %}
<script>
  $('#purchase_order_status, #purchase_order_list_company,#purchase_order_vendor,#purchase_order_bill_number').select2({
    width: "100%",
    
  });
  var role = true;
  if ("{{request.user.role}}" == "company admin" || "{{request.user.role}}" == "sales representative") {
    role = false;
  }
  var i = 1;

  function set_filters(){
    var data = {}
    data["purchase_order_status"] = $("#purchase_order_status").val()
    data["purchase_order_list_company"] = $("#purchase_order_list_company").val()
    data["purchase_order_vendor"] = $("#purchase_order_vendor").val()
    data["purchase_order_bill_number"] = $("#purchase_order_bill_number").val()
    

    return data
  }
  var order_false = [-1]
  var to_center = [3,4,6]
  var invisible_columns = [1]
  var filter_id = $("#purchase_order_status,#purchase_order_list_company,#purchase_order_vendor,#purchase_order_bill_number")

  var url = '{% url "purchase_order:purchase_order_list_ajax" %}';
  var columns = [
      { data: 'id', name: 'id' },
      { data: 'company', name: 'company' },
      { data: 'vendor', name: 'vendor' },
      { data: 'bill_number', name: 'bill_number' },
      { data: 'bill_date', name: 'bill_date' },
      { data: 'total_price', render: function ( number ) {return number.toLocaleString('en-IN', {maximumFractionDigits: 2, style: 'currency', currency: 'INR'})}, name: 'total_price' },
      { data: 'status', name: 'status' },
      { data: 'actions', name: 'id' },
    ]
    
</script>
{% comment %} <script src="{% static 'webapp/company/company_scripts.js' %}"></script> {% endcomment %}
<script src="{% static 'webapp/intailize_datatables.js' %}"></script>
{% comment %} <script src="{% static 'webapp/purchase_order/purchase_order_scripts.js' %}"></script> {% endcomment %}

<script>
 


$(document).on('click', '.company-list-clear' , function (){
  $("#purchase_order_status").val(null).trigger('change');
  $("#purchase_order_list_company").val(null).trigger('change');
  $("#purchase_order_vendor").val(null).trigger('change');
  $("#purchase_order_bill_number").val(null).trigger('change');
  $("#table").DataTable().destroy();
  intailize_datatables()
    });
 
</script>


{% endblock script %}