app_modules/reports/urls.py
from django.urls import path
from app_modules.reports import views

app_name = "reports"

urlpatterns = [
    # path("due-payment-list/", views.ReportByDuePaymentListView.as_view(), name="by_due_payment_list"),
    # path("due-payment-list-ajax/", views.ReportByDuePaymentDataTableAjaxPagination.as_view(), name="report_due_list_ajax"),
    # path("due-payment-table-print-ajax/", views.ReportByDueTablePrintAjaxView.as_view(), name="by_due_table_print_ajax"),
    
    path("zone-wise-collection-report/", views.ZoneWiseCollectionReport.as_view(), name="zone_wise_collection_report"),
    path("zone-wise-collection-report-ajax/", views.ZoneWiseCollectionReportAjax.as_view(), name="zone_wise_collection_report_ajax"),
    path("export/<str:type>/collection/", views.ExportCollectionReport.as_view(), name="export_collection_report"),

    path("daily-bill-report/", views.DailyBillReport.as_view(), name="daily_bill_report"),
    path("daily-bill-report-ajax/", views.DailyBillReportAjax.as_view(), name="daily_bill_report_ajax"),
    path("export/daily-bill-report/", views.ExportDailyBillReport.as_view(), name="export_daily_bill_report"),

    path("bill-summary-report/", views.BillSummaryReport.as_view(), name="bill_summary_report"),
    path("bill-summary-report-ajax/", views.BillSummaryReportAjax.as_view(), name="bill_summary_report_ajax"),
    path("export/bill-summary-report/", views.ExportBillSummaryReport.as_view(), name="export_bill_summary_report"),

    path("ledger-report/", views.LedgerReport.as_view(), name="ledger_report"),
    path("ledger-report-ajax/", views.LedgerReportAjax.as_view(), name="ledger_report_ajax"),
    path("export/ledger-report/", views.ExportLedgerReport.as_view(), name="export_ledger_report"),

    path("by-commision-list/", views.ReportByCommisionListView.as_view(), name="by_commision_list"),
    path("report-commision-list-ajax/",views.ReportByCommisionDataTableAjaxPagination.as_view(),name="report_commision_list_ajax"),
    path("report-comision-list-ajax/",views.ReportByCommisionCsvAjaxPagination.as_view(),name="by_commission_table_csv_ajax"),

    path("by-ml-list/", views.ReportByMlListView.as_view(), name="by_ml_list"),
    path("report-ml-list-ajax/",views.ReportByMlDataTableAjaxPagination.as_view(),name="report_ml_list_ajax"),
    path("by-ml-table-csv-ajax/", views.ReportByMlTaxTableCsvAjaxView.as_view(), name="by_ml_table_csv_ajax"),

    path("report-ml-list-total-calculation-ajax/",views.ReportByMlTotalCalculationAjax.as_view(),name="report_ml_list_ajax_total_calculation"),

    path("by-due-payment-list/", views.ReportByDuePaymentListView.as_view(),name="by_due_payment_list"),
    path("due-payment-list-ajax/", views.ReportByDuePaymentDataTableAjaxPagination.as_view(), name="report_due_list_ajax"),
    path("due-payment-table-csv-ajax/", views.ReportByDueTableCsvAjaxView.as_view(), name="by_due_table_csv_ajax"),

    path("load-customer/",views.LoadCustomer.as_view(),name="load_customer"),
]

unity_wholesale/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from app_modules.users.views import HomeView, DasboardTemplateView , CustomPasswordChangeView

from allauth.account import views as allauth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("dashboard/",DasboardTemplateView.as_view(), name="dashboard"),
    path("company/", include('app_modules.company.urls'), name="company"),
    path("product/",include("app_modules.product.urls")),
    path("users/", include('app_modules.users.urls')),
    path("vendors/", include('app_modules.vendors.urls')),
    path("order/", include('app_modules.order.urls')),
    path('accounts/password/change/',CustomPasswordChangeView.as_view(),name='account_change_password'),
    # path("accounts/password/set/", allauth_views.password_set, name="account_set_password"),
    # path("accounts/logout/", allauth_views.logout, name="account_logout"),
    # path("accounts/signup/", allauth_views.signup, name="account_signup"),
    # path("accounts/password/reset/", allauth_views.password_reset, name="account_reset_password"),
    path("accounts/", include("allauth.urls")),
    path("", HomeView.as_view(), name="home_view"),
    path("customers/", include('app_modules.customers.urls'), name="customers"),
    path("purchase-order/",include('app_modules.purchase_order.urls')),
    path("credit-memo/",include('app_modules.credit_memo.urls')),
    path("reports/",include('app_modules.reports.urls')),
    path("expanse-management/",include('app_modules.expanse_management.urls')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_modules/reports/models.py
from django.db import models
from app_modules.base.models import BaseModel
from app_modules.customers.models import Customer
from app_modules.order.models import OrderedProduct
from app_modules.users.models import User
from app_modules.product.models import Product
from django.utils.translation import gettext_lazy as _
# Create your models here.

class SalesRepCommissionCodeReport(BaseModel):
    
    EXCHANGE="exchange"
    TEXTABLE="textable"
    FREE_ITEM="free item"

    PRODUCT_LABEL_CHOICES= (
        (EXCHANGE,'Exchange'),
        (TEXTABLE,'Textable'),
        (FREE_ITEM,'Free Item')
    )
    order_product = models.ForeignKey(OrderedProduct, on_delete=models.CASCADE, related_name="order_product_report")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="report_product")
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE,null=True,related_name="report_customers")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sales_rep_report")
    product_commission_code = models.FloatField(verbose_name="Product Commission Code",default=0.00)
    total_sales_rep_commision = models.FloatField(verbose_name="Total Sales Rep Commission",default=0.00)
    unit_sold = models.PositiveIntegerField(_('Product Unit Sold'))
    unit_type = models.CharField(_('Product Unit Type'), max_length=50)
    product_label= models.CharField(_('Product Label'), choices = PRODUCT_LABEL_CHOICES, default=TEXTABLE, max_length=10)
    product_ml_quantity = models.FloatField(_("Product ML Quantity"), default=0)
    is_apply_ml = models.BooleanField( verbose_name="Is Apply ML Quantity", default=False)
    total_sold_piece = models.IntegerField(_("Total Sold Piece"))
    product_total_ml_quantity =  models.FloatField(_("Total Product ML Quantity"), default=0)
    ml_tax = models.FloatField(_("Product ML Tax"), default=0)
    product_cost_price = models.FloatField(verbose_name="Product Cost Price",default=0.00)
    product_wholesale_min_price = models.FloatField(verbose_name="Product Wholesale Min Price",default=0.00)
    product_wholesale_base_price = models.FloatField(verbose_name="Product Wholesale Base Price",default=0.00)
    product_retail_min_price = models.FloatField(verbose_name="Product Retail Min Price",default=0.00)
    product_retail_base_price = models.FloatField(verbose_name="Product Retail Base Price",default=0.00)
    product_sold_price = models.FloatField(verbose_name="Product Sold Price",default=0.00)

    def __str__(self):
        return self.created_by.role

app_modules/reports/views.py
import csv
from typing import Any, Dict
from django.shortcuts import render
from django.views.generic import ListView, View, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django_datatables_too.mixins import DataTableMixin
from app_modules.base.mixins import CompanyAdminLoginRequiredMixin, AccountantLoginRequiredMixin
from app_modules.company.models import CompanyUsers
from app_modules.customers.models import Customer, CustomerBill, Zone, CustomerPaymentBill
from app_modules.order.models import Order, OrderBill
from app_modules.reports.models import SalesRepCommissionCodeReport
from app_modules.users.models import User
from django.template.loader import get_template
from django.http import HttpResponse, JsonResponse
from django.db.models import Q, Sum, F, ExpressionWrapper, FloatField
from django.utils.dateparse import parse_date

from app_modules.order import utils
from datetime import datetime, timedelta
from num2words import num2words

# Create your views here.

class ZoneWiseCollectionReport(AccountantLoginRequiredMixin, ListView):
    template_name = "reports/collection-report/zone_wise_collection_report.html"
    model = OrderBill

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        if self.request.user.role in [User.COMPANY_ADMIN, User.ACCOUNTANT]:
            context["sales_rep"] = CompanyUsers.objects.filter(company__id=self.request.user.get_company_id,user__role=User.SALES_REPRESENTATIVE)
            context["customer_list"] = Customer.objects.filter(company__id=self.request.user.get_company_id,status=Customer.ACTIVE)
            context["zone_list"] = Zone.objects.filter(company__id=self.request.user.get_company_id)
        else:
            context["sales_rep"] = CompanyUsers.objects.filter(user__role=User.SALES_REPRESENTATIVE)
            context["customer_list"] = Customer.objects.filter(status=Customer.ACTIVE)
            context["zone_list"] = Zone.objects.all()
        return context


class ZoneWiseCollectionReportAjax(LoginRequiredMixin, DataTableMixin, View):
    model = OrderBill

    def get_queryset(self):
        qs = OrderBill.objects.all()
        
        if self.request.user.role in [User.COMPANY_ADMIN, User.ACCOUNTANT]:
            qs = qs.filter(customer__company__id = self.request.user.get_company_id)
        
        zone = self.request.GET.get("zone")
        start_date = self.request.GET.get("from_date")
        end_date = self.request.GET.get("to_date")
        
        # if start_date and end_date:
        #     qs =qs.filter(created_at__range=[start_date, end_date]).distinct()
        
        if start_date:
            start_date_obj = datetime.strptime(start_date, "%Y-%m-%d").date()
            qs = qs.filter(bill_date__gte = start_date_obj).distinct()

        if end_date:
            end_date_obj = datetime.strptime(end_date, "%Y-%m-%d").date()
            qs = qs.filter(bill_date__lte = end_date_obj).distinct()

        if zone:
            qs = qs.filter(customer__zone__id=zone).distinct()
        
        return qs.order_by("-id")

    def filter_queryset(self, qs):
        if self.search:
            return qs.filter(
                Q(customer__customer_name__icontains = self.search)
            )
        return qs
    
    def get_order_details(self, obj):
        t = get_template("reports/report_order_details.html")
        return t.render(
            {"order": obj.order }
        )
    
    def get_customer_details(self, obj):
        t = get_template("reports/report_customer_details.html")
        return t.render(
            {"customer_id": obj.customer}
        )
    
    def prepare_results(self, qs):
        return [
            {
                'id': o.id,
                'bill_date': f'{o.bill_date.strftime("%-d %B, %Y")}',
                'customer': self.get_customer_details(o),
                'customer__zone': o.customer.zone.zone_code if o.customer.zone else "-",
                'slip_no': o.slip_no if o.slip_no else "-",
                'bill_amount': o.bill_amount,
                'paid_amount': o.paid_amount,
            }
            for o in qs
        ]

    def get(self, request, *args, **kwargs):
        context_data = self.get_context_data(request)
        return JsonResponse(context_data)


class ExportCollectionReport(ListView):
    template_name = "reports/collection-report/export-collection-report.html"
    model = OrderBill

    def get(self, request, type):
        zone = self.request.GET.get("zone")
        start_date = self.request.GET.get("start_date")
        end_date = self.request.GET.get("end_date")

        queryset = OrderBill.objects.all()
        context = {}

        if self.request.user.role in [User.COMPANY_ADMIN, User.ACCOUNTANT]:
            queryset = queryset.filter(customer__company__id=self.request.user.get_company_id)

        if zone:
            queryset = queryset.filter(customer__zone__id = zone)
            zone = Zone.objects.filter(id = zone).last()
            context["zone"] = zone.zone_code
        
        backup_queryset = queryset

        if start_date:
            start_date_obj = datetime.strptime(start_date, "%Y-%m-%d").date()
            queryset = queryset.filter(bill_date__gte = start_date_obj).distinct()
            before_start_date = start_date_obj - timedelta(days=1)
            context["start_date"] = start_date_obj
        else:
            before_start_date = ""

        if end_date:
            end_date_obj = datetime.strptime(end_date, "%Y-%m-%d").date()
            queryset = queryset.filter(bill_date__lte = end_date_obj).distinct()
            context["end_date"] = end_date_obj
        else:
            end_date_obj = datetime.today().date()
            context["end_date"] = end_date_obj

        if type == "balance":
            customer_list = list(queryset.values_list("customer", flat=True).distinct())
            customers = Customer.objects.filter(status = Customer.ACTIVE, id__in = customer_list)
        else:
            customers = Customer.objects.filter(status = Customer.ACTIVE)

        collection_list = {}
        for customer in customers:
            customer_bills = queryset.filter(customer = customer)
            backup_customer_bills = backup_queryset.filter(customer = customer)

            total_payment_amount = 0
            total_bill_amount = 0
            before_start_date_bill_total = 0
            before_start_date_payment_total = 0
            bill_list = {}

            if start_date:
                start_date_obj = datetime.strptime(start_date, "%Y-%m-%d").date()
                before_start_date_payment_list = backup_customer_bills.filter(bill_date__lt = start_date_obj)

                if before_start_date_payment_list.count() > 0:
                    before_start_date_bill_total = before_start_date_payment_list.aggregate(total_bill_amount = Sum("bill_amount"))["total_bill_amount"]
                    before_start_date_payment_total = before_start_date_payment_list.aggregate(total_payment = Sum("paid_amount"))["total_payment"]

            before_end_date_payments = backup_customer_bills.filter(bill_date__lte = end_date_obj)
            
            if before_end_date_payments.count() > 0:
                total_bill_amount = before_end_date_payments.aggregate(total_bill_amount = Sum("bill_amount"))["total_bill_amount"]
                total_payment_amount = before_end_date_payments.aggregate(total_payment = Sum("paid_amount"))["total_payment"]

            else:
                if customer_bills.count() > 0:
                    total_bill_amount = customer_bills.aggregate(total_bill_amount = Sum("bill_amount"))["total_bill_amount"]
                    total_payment_amount = customer_bills.aggregate(total_payment = Sum("paid_amount"))["total_payment"]

            bill_list["customer_bills"] = customer_bills
            bill_list["before_start_date"] = before_start_date
            bill_list["before_start_date_bill_total"] = before_start_date_bill_total
            bill_list["before_start_date_payment_total"] = before_start_date_payment_total
            bill_list["total_payment_amount"] = total_payment_amount
            bill_list["total_bill_amount"] = total_bill_amount
            bill_list["total_pending_amount"] = total_bill_amount - total_payment_amount
            collection_list[customer] = bill_list

        context["collection_list"] = collection_list
        pdf = utils.render_to_pdf(self.template_name, context)

        return HttpResponse(pdf, content_type='application/pdf')

class ExportDailyBillReport(ListView):
    template_name = "reports/daily-bill-report/export_daily_bill_report.html"
    model = OrderBill

    def get(self, request):
        qs = OrderBill.objects.all()        
        if self.request.user.role in [User.COMPANY_ADMIN, User.ACCOUNTANT]:
            qs = qs.filter(customer__company__id = self.request.user.get_company_id)
        
        zone = self.request.GET.get("zone")
        start_date = self.request.GET.get("start_date")
        context = {}

        if start_date:
            start_date = datetime.strptime(start_date, "%Y-%m-%d").date()
            # end_date = datetime.strptime(end_date, "%Y-%m-%d").date()
            # qs =qs.filter(created_at__date__range=[start_date, end_date]).distinct()
            qs=qs.filter(created_at__date=start_date).distinct()
            context["start_date"]= start_date

        if zone:
            qs = qs.filter(customer__zone__id=zone).distinct()
            zone_obj = Zone.objects.filter(id = zone).last()
            if zone_obj:
                context["zone"] = zone_obj.zone_code
        
        context["order_bills"] = qs
        paid_total = qs.filter(status = OrderBill.COMPLETE)

        if paid_total:
            context["paid_total"] = paid_total.aggregate(total=Sum("paid_amount"))["total"]
        else:
            context["paid_total"] = 0.0
        

templates/reports/daily-bill-report/daily_bill_report.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Daily Bill Report{% endblock title %}

{% block style %}
<style>
.buttons-html5 {
    display:none;
 }
</style>
{% endblock style %}

{% block bodycontent %}

<div class="users-list-filter px-2">
    <div class="row border rounded py-2 mb-2 mx-n2">
        <div class="col-12 col-sm-6 col-lg-2">
            <label for="report-list-customer">Zone</label>
            <fieldset class="form-group">
                <select id="id_zone" class="select2-data-array form-control select2-list">
                    <option value="">All</option>
                    {% for zone in zone_list %}
                    <option value="{{zone.id}}">{{zone.zone_code}}</option>
                    {% endfor %}
                </select>
            </fieldset>
        </div>
        <div class="col-12 col-sm-6 col-lg-2">
            <label for="id_start_date">Date</label>
            <div class="" id="report-due-from-date">
                <input type="date" name="due_from_date" class="form-control" placeholder="From Date"  id="id_start_date">
            </div>
        </div>
        {% comment %} <div class="col-12 col-sm-6 col-lg-2">
            <label for="end_date">To Date</label>
            <div class="" id="report-due-to-date">
                <input type="date" name="end_date" class="form-control" placeholder="To Date"  id="id_end_date">
            </div>
        </div> {% endcomment %}
        <div class="col-12 col-sm-6 col-lg-8">
            <div class="d-flex justify-content-end">
                <button type="reset" class="btn btn-primary report-list-clear mt-2">Clear</button>
            </div>
        </div>
    </div>
</div>


<section id="file-export">
  <div class="row">
      <div class="col-12">
          <div class="card">
            <div class="card-header">
              <div class="d-flex flex-sm-row flex-column justify-content-between">
                <h4 class="card-title align-self-center">Daily Bill Report</h4>
                <div>
                    <button class="btn btn-primary export-report" data-url="{% url 'reports:export_daily_bill_report' %}" title="Export PDF">Export Report</button>
                </div>
              </div>
            </div>
              <div class="card-content ">
                  <div class="card-body">
                      <div class="table-responsive">
                          <table class="table table-striped table-bordered file-export" id="bill-table">
                              <thead>
                                  <tr>
                                    {% comment %} <th>Sr no</th> {% endcomment %}
                                    <th>Slip No</th>
                                    <th>Customer Name & Address</th>
                                    <th>Slip Date</th>
                                    <th>Amount</th>
                                    <th>Payment Status</th>
                                    <th>Update Date</th>
                                  </tr>
                              </thead>
                              <tbody>
                              </tbody>
                                <tfoot>
                                    <tr>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                    </tr>
                                </tfoot>                        
                          </table>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</section>
{% endblock %}

{% block script %}
    <script src="{% static 'app-assets/js/net_plug-ins_2.1.2_api_sum().js' %}"></script>
    <script>
        let startDateElement = document.getElementById("id_start_date")
        {% comment %} let endDateElement = document.getElementById("id_end_date") {% endcomment %}

        var today = new Date();
        var year = today.getFullYear();
        var month = String(today.getMonth() + 1).padStart(2, '0');
        var day = String(today.getDate()).padStart(2, '0');
        var dateString = `${year}-${month}-${day}`;

        startDateElement.value = dateString
        {% comment %} endDateElement.value = dateString {% endcomment %}

        $('.select2-list').select2({
            width: "100%",
        });

        function set_filters(){
            var data = {}
            data["zone"] = $("#id_zone").val()
            data["from_date"] = document.getElementById("id_start_date").value
            {% comment %} data["to_date"] = document.getElementById("id_end_date").value {% endcomment %}
            return data;
        }

        function initialize_datatable(){
            function statusDesign(status){
                if(status.toString().toLowerCase() == "paid"){
                    return "<span class='badge bg-light-success'>PAID</span>";
                }
                else {
                    return "<span class='badge bg-light-danger'>UNPAID</span>";
                }
            }

            $('#bill-table').DataTable({
                columnDefs: [{
                        orderable: false,
                        targets: []
                    },
                    {
                        "targets": "_all",
                        "className": "text-center",
                    }
                ],
                processing: true,
                language: {
                    processing: '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading...</span>'
                },
                serverSide: true,
                ajax: {
                    url: '{% url "reports:daily_bill_report_ajax" %}',
                    type: 'get',
                    data: set_filters(),
                },
                columns: [
                    {% comment %} { data: 'id', name: 'id' }, {% endcomment %}
                    { data: 'slip_no', name: 'slip_no' },
                    { data: 'customer', name: 'customer' },
                    { data: 'created_at', name: 'created_at' },
                    { data: 'bill_amount', render: function ( number ) {return number.toLocaleString('en-IN', {maximumFractionDigits: 2, style: 'currency', currency: 'INR'})}, name: 'bill_amount' },
                    { data: 'payment_status', render: function ( status ) {return statusDesign(status) }, name: 'payment_status' },
                    { data: 'updated_at', name: 'updated_at' },                    
                ],
                {% comment %} rowCallback: function (nRow, aData, iDisplayIndex) {
                    var oSettings = this.fnSettings();
                    $("td:first", nRow).html(oSettings._iDisplayStart + iDisplayIndex + 1);
                    return nRow;
                }, {% endcomment %}
                footerCallback: function ( row, data, start, end, display ) {
                    var api = this.api(), data;
                    var intVal = function ( i ) {
                        return typeof i === 'string' ?
                            i.replace(/[\$,]/g, '')*1 :
                            typeof i === 'number' ?
                                i : 0;
                    };

                    var monTotal = api
                        .column( 3 )
                        .data()
                        .reduce( function (a, b) {
                            return intVal(a) + intVal(b);
                        }, 0 );
                    
                    $( api.column( 0 ).footer() ).html('Total Bill Amount');
                    $( api.column( 3 ).footer() ).html(monTotal.toLocaleString('en-IN', {maximumFractionDigits: 2, style: 'currency', currency: 'INR'}));
                },
            });
        }

        initialize_datatable();

        $(document).on("change", ".select2-list", function(){
            $("#bill-table").DataTable().destroy();
            initialize_datatable();
        });

        $(document).on("input", "#id_start_date", function(){
            $("#bill-table").DataTable().destroy();
            initialize_datatable();
        });

        $(document).on("click",".report-list-clear",function(){
            document.getElementById("id_start_date").value = ""
            document.getElementById("id_end_date").value = ""
            $("#bill-table").DataTable().destroy();
            initialize_datatable();
        });

        $(document).on("click", ".export-report" , function() {
            var url = $(this).data("url");
            var zone = $("#id_zone").val();
            var start_date = $("#id_start_date").val();
            {% comment %} var end_date = $("#id_end_date").val(); {% endcomment %}
    
            $.ajax({
                type: "GET",
                url: url,
                data: {
                    "zone": zone,
                    "start_date": start_date,
                    {% comment %} "end_date": end_date, {% endcomment %}
                },
                success: function (data) {
                    var file = new Blob([data], {type: 'application/pdf'});
                    var fileURL = URL.createObjectURL(file);
                    window.open(fileURL);
                }
            });
        });
    </script>
    
{% endblock script %}

templates/reports/daily-bill-report/export_daily_bill_report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily Bill Report</title>
    <style>
        @page {
            margin: 25px 15px;

            @frame footer_frame {
                -pdf-frame-content: footer_content;
                left: 10pt; right: 10pt; width: 1050pt; top: 810pt; height: 20pt;
            }
        }

        table, tr, td, th, tbody, thead, tfoot {
            page-break-inside: auto !important;
            font-size: 10pt;
        }

        .text-end{
            text-align: right !important;
        }

        .mb-3 {
            margin-bottom: 3rem !important;
        }

        #main-table > table {
            width: 90%;
            text-align: center;
            border-collapse: separate; /* Don't collapse */
            border-spacing: 0;
        }

        #main-table > table th {
            /* Apply both top and bottom borders to the <th> */
            border-top: 2px solid;
            border-bottom: 2px solid;
            border-right: 2px solid;
            padding-top: 3px;
            padding-bottom: 3px;
            font-size: 9pt !important;
        }

        #main-table > table td {
            padding-top: 3px;
        }

        #main-table > table th:first-child
        {
            /* Apply a left border on the first <td> or <th> in a row */
            border-left: 2px solid;
        }

        #main-table > table thead th {
            position: sticky;
            top: 0;
            background-color: #edecec;
        }
    </style>
</head>
<body>
    <div class="mb-3">
        <table style="width: 100%">
            <tr>
                <td style="width:50%">
                    {% if zone %}
                        Zone: <b>{{ zone }}</b>
                    {% endif %}
                </td>

                <td style="width:50%" class="text-end">
                    <b>BILL REPORT</b>
                    {% if start_date %}
                        ( {{ start_date|date:"d-m-Y" }} )
                    {% endif %}
                </td>
            </tr>
        </table>
    </div>

    <div id="main-table">
        <table>
            <thead>
                <th style="width:10%">SLIP NO.</th>
                <th style="width:25%">CUSTOMER NAME & ADDRESS</th>
                <th style="width:15%">SLIP DATE</th>
                <th style="width:15%">AMOUNT</th>
                <th style="width:15%">PAYMENT STATUS</th>
                <th style="width:20%">UPDATE DATE</th>
            </thead>
            <tbody>
                {% for order_bill in order_bills %}
                <tr style="margin-bottom: 20px">
                    <td valign="top">
                        {{ order_bill.slip_no }}
                    </td>
                    <td valign="top">
                        <div>{{order_bill.customer.customer_name}} <br>
                        Zone: {{order_bill.customer.zone.zone_code}} &nbsp&nbsp {{order_bill.customer.area}}</div>
                    </td>
                    <td>
                        {{ order_bill.created_at|date:"d-m-Y" }}
                    </td>
                    <td style="text-align: center;">
                        <b>{{ order_bill.bill_amount }}</b>
                    </td>
                    <td style="text-align: center;">
                        {% if order_bill.status == 'complete' %}
                        <b>PAID</b>
                        {% else %}
                        <b>UNPAID</b>
                        {% endif %}
                    </td>
                    <td style="text-align: center;">
                        {% if order_bill.updated_at|date:"d-m-Y h:i A" != order_bill.created_at|date:"d-m-Y h:i A" %}
                            {{ order_bill.updated_at|date:"d-m-Y h:i A" }}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            {% if order_bills %}
            <tfoot>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <div>Cash Total :</div>
                        <div>Credit Total :</div>
                    </td>
                    <td>
                        <div style="margin-right: 20px; text-align: center">
                            <div><b>{{ paid_total }}</b></div>
                            <div><b>{{ unpaid_total }}</b></div>
                        </div>
                    </td>
                    <td></td>
                </tr>
            </tfoot>
            {% endif %}
        </table>
    </div>

    <table id="footer_content">
        <tr>
            <td>Date: {% now "d-m-Y h:i A" %}</td>
            <td>page <pdf:pagenumber> of <pdf:pagecount></td>
        </tr>
    </table>
</body>
</html>