app_modules/order/urls.py
from django.urls import path
from app_modules.order.views import (
    AssignDriverOrderView,
    AssignedDriverOrderDataTableAjaxPagination,
    OrderCreateView,
    GetCustomersProductsAjax,
    GetCustomerDetailsAjax,
    GetProductUnitTypesAjax,
    AddProductDetailsInOrderListAjax,
    GetProductPriceStockAjax,
    OrderListView,
    OrderListAjax,
    OrderBillListAjax,
    OrderLogDatatableAjaxView,
    OrderTablePrintAjaxView,
    OrderUpdateView,
    AjaxGetUpdateOrderProductDetails,
    GetProductForOrderByBarcodeAjax,
    GetWarehouseProductsAjax,
    CarCreateView,
    CarListView,
    CarDataTableAjaxPagination,
    CarUpdateView,
    CarDeleteAjaxView,
    OrderLogAjaxView,
    OrderLogAjaxView,
    PlanRouteAjaxView,
    DriverAssignRoutesAjax,
    AssignedDriverOrderList,
    OrderDetailView,
    OrderPackingView,
    RenderOptimizedMap,
    SetOrderProductPackingDetailAjaxView,
    DetailViewAssignDriverOrderView,
    SetOrderShippedAjaxView,
    OrderCancelAjaxView,
    AssignDriverRoutesCreateView,
    LoadDriverAjaxView,
    SetOrderUndeliveredAjaxView,
    DetailViewAssignDriverOrderForCompleteView,
    DriverAssignRoutesOrderStatusAjax,
    DetailViewAssignDriverOrderForCancelView,
    SetOrderCompletedAjaxView,
    BrandSearchAjaxView,
    OrderSearchAjaxView,
    ProductSearchAjaxView,
    AddReplacementProductAjaxView,
    GenerateBillAjaxView,
    DispatchOrderListView,
    GenerateBillView,
    PrintDispatchRoutesView,
    OrderBillListView,
    TransferStockView,
    StockDetailAjaxView,
    UpdateProductAjaxView,
    SetInformAdminReplacement,
    ReplacementProductAjaxView,
    CompleteReplacementAjaxView,
    FetchShortestRouteView,

)

app_name = "order"

urlpatterns = [
    path("type/<str:type>/create/",OrderCreateView.as_view(),name="order_create"),
    path("<int:pk>/details/", OrderDetailView.as_view(), name="order_detail"),
    path("<int:pk>/packing/", OrderPackingView.as_view(), name="order_packing"),
    path("car-create/", CarCreateView.as_view(), name="car_create"),
    path("car-list/", CarListView.as_view(), name="car_list"),
    path("car-list-ajax/", CarDataTableAjaxPagination.as_view(), name="car_list_ajax"),
    path("car/<int:pk>/update/", CarUpdateView.as_view(), name="car_update"),
    path("car-delete/", CarDeleteAjaxView.as_view(), name="car_delete"),
    path("ajax-get-customers-products/", GetCustomersProductsAjax.as_view(),name="get_customers_products_ajax"),
    path("ajax-get-customer-details/", GetCustomerDetailsAjax.as_view(),name="get_customer_details_ajax"),
    path("ajax-get-product-unit-type/", GetProductUnitTypesAjax.as_view(), name = "ajax_get_product_unit_type" ),
    path("ajax-get-product-price-stock/", GetProductPriceStockAjax.as_view(), name = "ajax_get_product_price_stock" ),
    path("ajax-add-product-details-in-order-list/",AddProductDetailsInOrderListAjax.as_view(),name="ajax_add_product_details_in_order_list"),
    path("",OrderListView.as_view(),name="order_list"),
    path("bills/", OrderBillListView.as_view(),name="order_bill_list"),
    path("draft-orders/",OrderListView.as_view(),name="draft_order_list"),
    path("dispatch/",DispatchOrderListView.as_view(),name="dispatch_order_list"),
    
    path("ajax-order-list/",OrderListAjax.as_view(),name="order_list_ajax"),
    path("ajax-order-bill-list/",OrderBillListAjax.as_view(),name="order_bill_list_ajax"),
    path("type/<str:type>/<int:pk>/update",OrderUpdateView.as_view(),name="order_update"),
    path("ajax-get-update-order-product-details/",AjaxGetUpdateOrderProductDetails.as_view(),name="ajax_get_update_order_product_details"),
    path("ajax-get-product-for-order-by-barcode/",GetProductForOrderByBarcodeAjax.as_view(),name="ajax_get_product_for_order_by_barcode"),
    path("ajax-get-warehouse-products",GetWarehouseProductsAjax.as_view(),name="get_warehouse_products_ajax"),
    path('<int:pk>/order-log-list-ajax/', OrderLogAjaxView.as_view(), name='order_log_ajax'),
    path('order-log-list-ajax-datatable/', OrderLogDatatableAjaxView.as_view(), name='order_log_ajax_datatable'),
    path('order-table-print-ajax', OrderTablePrintAjaxView.as_view(), name='order_table_print_ajax'),
    path('<int:pk>/generate-bill/', GenerateBillView.as_view(), name='generate_bill'),
    path('order-assign-driver', AssignDriverOrderView.as_view(), name='assign_driver'),
    path('plan-route-ajax', PlanRouteAjaxView.as_view(), name='plan_route_ajax'),
    path('driver-assigned-route-ajax', DriverAssignRoutesAjax.as_view(), name='assign_route'),
    path('driver-assigned-route-status-ajax', DriverAssignRoutesOrderStatusAjax.as_view(), name='order_route_status_complete'),
    
    path("assigned-driver-order-list/",AssignedDriverOrderList.as_view(),name="assigned_order_driver_list"),
    path("assigned-driver-route-create/",AssignDriverRoutesCreateView.as_view(),name="assigned_driver_route_create"),
    path("assigned-driver-route-create/load-driver",LoadDriverAjaxView.as_view(),name="load_driver"),

    path("transfer-stock/", TransferStockView.as_view(), name="transfer_stock"),
    path("stock/details/", StockDetailAjaxView.as_view(), name="stock_details"),
    path("update/product/", UpdateProductAjaxView.as_view(), name="update_order_product"),
    path("replacement-products-list-ajax/", ReplacementProductAjaxView.as_view(), name="replacement_product_list"),
    path("replacement/complete/", CompleteReplacementAjaxView.as_view(), name="set_replacement_complete"),

    path("assigned-driver-order-ajax/",AssignedDriverOrderDataTableAjaxPagination.as_view(),name="assign_driver_order_ajax"),
    path("<int:assigned_route>/render-optimize-route-map/",RenderOptimizedMap.as_view(),name="render_optimize_route_map"),

    path("<int:assigned_route>/detail-assigned-order/",DetailViewAssignDriverOrderView.as_view(),name="detail_assigned_order"),
    path("<int:assigned_route>/detail-assigned-order-complete/",DetailViewAssignDriverOrderForCompleteView.as_view(),name="detail_assigned_order_complete"),
    path("<int:assigned_route>/detail-assigned-order-cancel/",DetailViewAssignDriverOrderForCancelView.as_view(),name="detail_assigned_order_cancel"),
    
    path("<int:assigned_route>/detail-assigned-order-location/",RenderOptimizedMap.as_view(),name="detail_assigned_order_location"),
    
    path('set-order-product-packing-detail', SetOrderProductPackingDetailAjaxView.as_view(), name='set_order_product_packing_detail'),
    path('set-order-shipped', SetOrderShippedAjaxView.as_view(), name='set_order_shipped'),
    path('set-order-undelivered', SetOrderUndeliveredAjaxView.as_view(), name='set_order_undelivered'),
    path('set-order-completed', SetOrderCompletedAjaxView.as_view(), name='set_order_completed'),
    path('cancel-order', OrderCancelAjaxView.as_view(), name='cancel_order'),

    path("brand/search/", BrandSearchAjaxView.as_view(), name="brand_search"),
    path("order/search/", OrderSearchAjaxView.as_view(), name="order_search"),
    path("order-product/search/", ProductSearchAjaxView.as_view(), name="order_product_search"),

    path("replacement/product/add/", AddReplacementProductAjaxView.as_view(), name="add_replacement_product"),
    path("print/dispatch-routes/<int:pk>", PrintDispatchRoutesView.as_view(), name="print_dispatch_routes"),
    path("set-inform-admin-for-replacement", SetInformAdminReplacement.as_view(), name="set_inform_admin_for_replacement"),

    path("generate/bill/<str:type>", GenerateBillAjaxView.as_view(), name="generate_bill_form"),
    path('fetch_shortest_route/', FetchShortestRouteView.as_view(), name='fetch_shortest_route'),
]

app_modules/product/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from app_modules.product.views import (
    AddStockFromCSVFormView,
    BrandListView,
    BrandCreateView,
    BrandUpdateView,
    BrandDataTablesAjaxPagination,
    BrandDeleteAjaxView,

#     CategoryListView,
#     CategoryCreateView,
#     CategoryUpdateView,
#     CategoryDataTablesAjaxPagination,
#     CategoryDeleteAjaxView,
    ProductCreateFromCSVFormView,

#     SubCategoryListView,
#     SubCategoryCreateView,
#     SubCategoryUpdateView,
#     SubCategoryDataTablesAjaxPagination,
#     SubCategoryDeleteAjaxView,

    ProductListView,
    ProductCreateView,
    ProductUpdateView,
    ProductDataTablesAjaxPagination,
    ProductDeleteAjaxView,
    VehicleCreateAjaxView,

    ProductPriceListView,
    ProductPriceDataTablesAjaxPagination,
    ProductPriceUpdateAjaxView,

    ManageProductStock,
    LoadWarehouse,
    LoadProduct,
    TransferStockAdd,
    LoadAvailableStock,
    WarehouseProuctstockUpdateView,
    UpdateStock,
    ProdcutStockHistoryListView,
    ProdcutStockHistoryDataTablesAjaxPagination,
    StockUpdateAjaxView,
    StockFormAjaxView,
    TransferStockView,
    
    ProductDetailView,
    BarcodeGenerateView,
    ProdcutBarcodeDataTablesAjaxPagination,
    DeleteBarcodeAjaxView,
    preview_csv,
    
    SearchAjaxView,

    ProductSearchAjaxView,
    ProductPriceAjaxView,
)


app_name = "product"

urlpatterns = [

     path("brands/", BrandListView.as_view(), name="list_brand"),
     path("brands/add/", BrandCreateView.as_view(), name="add_brand"),
     path("brands/<str:pk>/update/",
          BrandUpdateView.as_view(), name="update_brand"),
     path('brands/ajax/',
          BrandDataTablesAjaxPagination.as_view(), name='brands-list-ajax'),
     path("brand-delete-ajax/", BrandDeleteAjaxView.as_view(), name="delete_brand"),



     path("", ProductListView.as_view(), name="list_product"),
     path("add/", ProductCreateView.as_view(), name="add_product"),
     path("<str:pk>/update/",
          ProductUpdateView.as_view(), name="update_product"),
     path("vehicle/add/", VehicleCreateAjaxView.as_view(), name="add_vehicle"),
      
     path("ajax/",
          ProductDataTablesAjaxPagination.as_view(), name='product-list-ajax'),

     path("price/", ProductPriceListView.as_view(),
          name="list_product_price"),
     path('price/ajax/',
          ProductPriceDataTablesAjaxPagination.as_view(), name='product-price-list-ajax'),
     path("price/<int:pk>/update/",
          ProductPriceUpdateAjaxView.as_view(), name="update_product_price"),
     path("product-delete-ajax/", ProductDeleteAjaxView.as_view(), name="delete_product"),
         
     path("product-create-from-csv/", ProductCreateFromCSVFormView.as_view(), name="product_create_from_csv"),
     path("add-stock-from-csv/", AddStockFromCSVFormView.as_view(), name="add_stock_from_csv"),
     path("manage-stocks/", ManageProductStock.as_view(), name="manage_stocks"),
     path('manage-stocks/load_warehouse/',LoadWarehouse.as_view(),
         name='load_warehouse'),
     
     path('transfer-stocks/load_product/',LoadProduct.as_view(),
         name='load_product'),
     path("load-available-stock", LoadAvailableStock.as_view(), name="load_available_stock"),
     path("transfer-stock-add/", TransferStockAdd.as_view(), name="transfer_stock_add"),

     path('manage-stocks/get_form/',WarehouseProuctstockUpdateView.as_view(),
         name='get_form'),
     path('manage-stocks/update_stock/',UpdateStock.as_view(),
         name='update_stock'),

     path("list-product-history/",
          ProdcutStockHistoryListView.as_view(), name="list_product_history"),
     path("list-product-history/ajax/",
          ProdcutStockHistoryDataTablesAjaxPagination.as_view(), name='stock_history'),

     path("stock/<int:pk>/update/", StockUpdateAjaxView.as_view(), name="stock_update"),
     path("stock/form/", StockFormAjaxView.as_view(), name="stock_form_url"),
     

     path("transfer-stocks/", TransferStockView.as_view(), name="transfer_stocks"),

     path('<int:pk>/details/', ProductDetailView.as_view(), name="product_detail"),
     path('generate-barcode/barcode/', BarcodeGenerateView.as_view(), name="generate_barcode"),
     path("product-barcode-list/ajax/",ProdcutBarcodeDataTablesAjaxPagination.as_view(), name="product_barcode_list"),
     path('delete-barcode-ajax/',DeleteBarcodeAjaxView.as_view(), name='delete_barcode'),

     path("search/", SearchAjaxView.as_view(), name="search_url"),

     path('csv-list-preview/', preview_csv, name='csv_list_preview'),

     path("product/search/", ProductSearchAjaxView.as_view(), name="product_search"),
     path("product/price/", ProductPriceAjaxView.as_view(), name="get_product_price"),
     
     # path("discount/list", DiscountListView.as_view(), name="discount_list"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

unity_wholesale/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from app_modules.users.views import HomeView, DasboardTemplateView , CustomPasswordChangeView

from allauth.account import views as allauth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("dashboard/",DasboardTemplateView.as_view(), name="dashboard"),
    path("company/", include('app_modules.company.urls'), name="company"),
    path("product/",include("app_modules.product.urls")),
    path("users/", include('app_modules.users.urls')),
    path("vendors/", include('app_modules.vendors.urls')),
    path("order/", include('app_modules.order.urls')),
    path('accounts/password/change/',CustomPasswordChangeView.as_view(),name='account_change_password'),
    # path("accounts/password/set/", allauth_views.password_set, name="account_set_password"),
    # path("accounts/logout/", allauth_views.logout, name="account_logout"),
    # path("accounts/signup/", allauth_views.signup, name="account_signup"),
    # path("accounts/password/reset/", allauth_views.password_reset, name="account_reset_password"),
    path("accounts/", include("allauth.urls")),
    path("", HomeView.as_view(), name="home_view"),
    path("customers/", include('app_modules.customers.urls'), name="customers"),
    path("purchase-order/",include('app_modules.purchase_order.urls')),
    path("credit-memo/",include('app_modules.credit_memo.urls')),
    path("reports/",include('app_modules.reports.urls')),
    path("expanse-management/",include('app_modules.expanse_management.urls')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/order/assigned__order_driver_list.html
{% extends 'base.html' %}

{% block title %}
Assigned Driver
{% endblock title %}


{% block bodycontent %}

{% comment %} <div class="users-list-filter px-2">
    <div class="row border rounded py-2 mb-2 mx-n2">
        <div class="col-12 col-sm-6 col-lg-3">
        <label for="status-list-car">Status</label>
        <fieldset class="form-group">
          <select id="status-list-car" class="form-control">
            <option value="">All</option>
                {% for data in status_choices %}
                <option value="{{data.0}}">{{data.1}}</option>
                {% endfor %}
            </select>
        </fieldset>
    </div>
    
    <div class="col-12 col-sm-6 col-lg-3">
    </div>
    <div class="col-12 col-sm-6 col-lg-3">
    </div>
    <div class="col-12 col-sm-6 col-lg-2">
    </div>
    
    <div class="col-12 col-sm-6 col-lg-1 mt-1 d-flex align-items-center">
        <button type="reset" class="btn btn-primary btn-block car-list-clear glow mb-0">Clear</button>
    </div>
</div> {% endcomment %}


<section id="file-export">
  <div class="row">
      <div class="col-12">
          <div class="card">
            <div class="card-header">
              <div class="d-flex flex-sm-row flex-column justify-content-between">
                <h4 class="card-title align-self-center">Assigned Order Driver List</h4>
                <a href="{% url 'order:assigned_driver_route_create' %}" class="btn btn-primary ml-sm-1">Add</a>
              </div>
            </div>
              <div class="card-content ">
                  <div class="card-body">
                      <div class="table-responsive">
                          <table class="table table-striped table-bordered file-export" id="table">
                              <thead>
                                  <tr>
                                    <th>Sr no</th>
                                    <th>Driver Name</th>
                                    <th>Date</th>
                                    <th>Route Name</th>
                                    <th>Order Count</th>
                                    <th>Status</th>
                                    <th class="text-center">Actions</th>
                                  </tr>
                              </thead>
                              <tbody>
                                
                                {% comment %} {% for object in object_list %}
                                <tr>
                                    <td> {{forloop.counter}} </td>
                                    <td> {{object.driver.full_name}} </td>
                                    <td> {{object.name}} </td>
                                    <td> {{object.get_order_count}} </td>
                                </tr>
                                {% endfor %} {% endcomment %}

                              </tbody>
                          </table>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</section>
{% endblock %}

{% block script %}

<script>


    function initialize_datatable(){
    $('#table').DataTable({
        columnDefs: [{
            orderable: false,
            targets: [3,4,-1,-2]
        },],
        order: [[2, 'desc']],

        // Ajax for pagination
        processing: true,
        language: {
            processing: '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading...</span>'
        },
        serverSide: true,
        ajax: {
            url: '{% url "order:assign_driver_order_ajax" %}',
            type: 'get',
        },
        columns: [
            // data: json key from prepare_results, name: model field name
            { data: 'id', name: 'id' },
            { data: 'name', name: 'name' },
            { data: 'date', name: 'date' },
            { data: 'route_name', name: 'route_name' },
            { data: 'order_count', name: 'order_count' },
            { data: 'status', name: 'status' },
            { data: 'action', name: 'action' },
            
        ],
        rowCallback: function (nRow, aData, iDisplayIndex) {
            var oSettings = this.fnSettings();
            $("td:first", nRow).html(oSettings._iDisplayStart + iDisplayIndex + 1);
            return nRow;
        },
    });
}

    initialize_datatable();

    $("#status-list-car").on("change", function() {
        $("#table").DataTable().destroy();
        initialize_datatable()
    });

    $(".car-list-clear").on("click",function(){
        $("#status-list-car").val(null).trigger('change');
        $("#table").DataTable().destroy();
        initialize_datatable()
    })


</script>

{% endblock script %}

templates/order/form_assign_driver_route.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% if form.instance.id %}
Update
{% else %}
Add Route
{% endif %}
{% endblock title %}

{% block bodycontent %}
<section id="action-form-layout">
    <div class="row match-height">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            {% if form.instance.id %}
            <h4 class="card-title">Update Route</h4>
            {% else %}
            <h4 class="card-title">Add Route</h4> 
            {% endif %}
          </div>
          <div class="card-content">
            <div class="card-body">
              <form action="" method="post" novalidate>
                {% csrf_token %}
                
                {% if user.role == 'super admin' %}
                  
                <div class="row">
                  <div class="col-md-6 col-12">
                    <div class="form-group row">
                      <label class="col-md-3 col-form-label" for="horizontal-form-1">Company<span style="color: red;">*</span></label>
                      <div class="col-md-9">
                        <select name="company" class="select2-data-array form-control select2-list" placeholder="company" required = "" id="id_company" onchange = loadDriver()>
                            <option value="" selected>---------</option>
                            {% for company in company_list  %}
                            <option value="{{company.id}}">{{company.company_name}}</option>
                            {% endfor %}
                          </select>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                    <div class="col-md-6 col-12">
                      <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="horizontal-form-1">{{form.driver.label}}{% if form.driver.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                        <div class="col-md-9">
                            <select name="driver" class="select2-data-array form-control select2-list" placeholder="driver" required = "" id="id_driver">
                                <option value="" selected>---------</option>
                              </select>
                          {% if form.driver.errors %}
                              {% for error in form.driver.errors %}
                                <p style="color: red;">{{error}}</p>
                              {% endfor %}
                          {% endif %}
                        </div>
                      </div>
                    </div>
                {% else %}
                     <input type="hidden" name="company" id="id_company" value="{{user.get_company_id}}">
                     <div class="row">
                        <div class="col-md-6 col-12">
                          <div class="form-group row">
                            <label class="col-md-3 col-form-label" for="horizontal-form-1">{{form.driver.label}}{% if form.driver.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                            <div class="col-md-9">
                              {{form.driver}}
                              {% if form.driver.errors %}
                                  {% for error in form.driver.errors %}
                                    <p style="color: red;">{{error}}</p>
                                  {% endfor %}
                              {% endif %}
                            </div>
                          </div>
                        </div>
                {% endif %}
                
                  <div class="col-md-6 col-12">
                    <div class="form-group row">
                      <label class="col-md-3 col-form-label" for="horizontal-form-2">{{form.name.label}}{% if form.name.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                      <div class="col-md-9">
                        {{form.name}}
                        {% if form.name.errors %}
                            {% for error in form.name.errors %}
                              <p style="color: red;">{{error}}</p>
                            {% endfor %}
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                    <div class="col-md-6 col-12">
                      <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="horizontal-form-1">{{form.date.label}}{% if form.date.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                        <div class="col-md-9">
                          {{form.date}}
                          {% if form.date.errors %}
                              {% for error in form.date.errors %}
                                <p style="color: red;">{{error}}</p>
                              {% endfor %}
                          {% endif %}
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6 col-12">
                        <div class="form-group row">
                          <label class="col-md-3 col-form-label" for="horizontal-form-1">{{form.start_location.label}}{% if form.start_location.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                          <div class="col-md-9">
                            {% if user.role == 'company admin' or user.role == 'sales representative' %}
                            {{form.start_location}}
                            {% else %}
                            <select name="start_location" class="select2-data-array form-control select2-list" placeholder="start_location" required = "" id="id_start_location">
                                <option value="" selected>---------</option>
                              </select>
                            {% endif %}
                            {% if form.start_location.errors %}
                                {% for error in form.start_location.errors %}
                                  <p style="color: red;">{{error}}</p>
                                {% endfor %}
                            {% endif %}
                          </div>
                        </div>
                      </div>
                </div>
                
                  {% if form.instance.id %}
                  <button type="submit" class="btn btn-primary mr-2"><i class="ft-edit mr-1"></i>Update</button>
                  {% else %}
                  <button type="submit" class="btn btn-primary mr-2"><i class="ft-check-square mr-1"></i>Save</button>
                  {% endif %}
                <a href="{% url 'order:assigned_order_driver_list' %}"><button type="button" class="btn btn-secondary"><i class="ft-x mr-1"></i>Cancel</button></a>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock bodycontent %}

{% block script %}
<script src="{% static 'webapp/custom.js' %}"></script>
<script>
    function loadDriver(){
        var company = document.getElementById('id_company');
        var driver_id = document.getElementById('id_driver');
        var start_location = document.getElementById('id_start_location');
        driver_id.innerHTML = '';
        start_location.innerHTML = '';


        $.ajax({
            type: "GET",
            url: "{% url 'order:load_driver' %}",
            data: {
                "company_id": company.value,
            },
            success: function (data) {
                $("#id_driver").empty().append("<option value=''>---------</option>");
                $("#id_start_location").empty().append("<option value=''>---------</option>");
                data.driver.forEach(element => {
                    var option = document.createElement("option");
                    option.value = element.id;
                    option.text = element.full_name;
                    driver_id.options.add(option);
                })
                data.warehouse.forEach(element => {
                    var option = document.createElement("option");
                    option.value = element.id;
                    option.text = element.name;
                    start_location.options.add(option);
                })

                
            }
        })


    }
</script>



{% endblock script %}

templates/order/get_customers_products.html
{% if company_customers %}
    {% for company_customer in company_customers %}
        <option data-area="{{ company_customer.area }}" value="{{company_customer.id}}">{{company_customer.customer_name}} [{{company_customer.customer_type.title}}]</option>
    {% endfor %}
{% endif %}

{% if company_warehouses %}
    {% for company_warehouse in company_warehouses  %}
        <option value="{{company_warehouse.id}}">{{company_warehouse.name}}</option>
    {% endfor %}
{% endif %}

{% if company_products %}
    {% for company_product in company_products %}
        <option value="{{company_product.id}}">{{company_product.name}} {% if company_product.vehicle %}({{company_product.vehicle.name}}) {% endif %}</option>
    {% endfor %}
{% endif %}

{% if warehouse_products %}
    {% for warehouse_product in warehouse_products %}
        <option value="{{warehouse_product.product.id}}">{{warehouse_product.product.name}}</option>
    {% endfor %}
{% endif %}

templates/order/get_order_action_button.html
<div class="row">
<center>
    <label data-id="{{obj.id}}" data-url="{{logs_url}}" title="Logs" data-toggle="modal" data-target="#default" class="danger p-0 mr-2 order-log-history-btn details-btn"><i class="ft-clock font-medium-3" style="color: #975AFF;"></i></label>
    
    {% if print_table_url %}
    <label data-id="{{obj.id}}" data-url="{{print_table_url}}" title="Print" data-toggle="modal" data-target="#default" class="danger p-0 mr-2 order-print-btn  details-btn"><i class="ft-printer font-medium-3" style="color: #975AFF;"></i></label>
    {% endif %}

    {% if update_url %}    
    <a href="{{update_url}}" title="Edit"><i class="ft-edit font-medium-3 mr-2"></i></a>
    {% endif %}

    <a href="{{detail_url}}" title="View"><i class="ft-eye font-medium-3 mr-2"></i></a>
    
    <!-- <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" name="customCheck" id="custom-check-2" value="{{obj.id}}">
        <label class="custom-control-label" for="custom-check-2"><span>Assign Driver</span></label>
      </div> -->
    
    {% if obj.status in 'packed' and user.role in "company admin,sales representative" %}
    <input type="checkbox" name='order_checkbox' class="order_checkbox" value='{{obj.id}}' id="id_order_checkbox">
    <label for="id__{{obj.id}}_order_checkbox"></label>
    {% endif %}

    {% if is_dispatch %}
    <a href="javascript:void(0);" class="dispatch-btn" data-id="{{obj.id}}" data-url="{% url 'order:assign_driver' %}" title="Dispatch"><i class="ft-truck font-medium-3 mr-2"></i></a>
    {% endif %}
      
</center>
</div>